#!/usr/bin/env python
"""
Script Name: start_workflow.py
Generated by: picasso-workflow GUI
Generated on: 2026-02-03 17:01:12
Workflow type: Aggregation Workflow
"""
import os
from picasso import io
from picasso_workflow.metaworkflow import AggregationWorkflowCoordinator


# Confluence configuration (set via environment variables)
confluence_url = "https://mibwiki.biochem.mpg.de"
confluence_token = os.getenv('CONFLUENCE_BEARER')
confluence_space = "~hgrabmayr"
base_page = "pw-GUI-test"


# Dataset configuration
datasets = {
    '#tags': [
        'Pos3_L2-Rim1',
        'Pos3_L6',
        'Pos3_R2-PSD95',
        'Pos3_R3-GluA1',
        'Pos3_R4-Munc13',
    ],
    'filepath': [
        os.path.join('/', 'fs', 'mpib', 'pool-miblab1', 'users', 'schentarra', 'z_microscopy_raw', '260120_neurons#48_div16_GluA1-Fv-clasp_live', 'Rim1_rab_L2_60pM_18mW_1', 'Rim1_rab_L2_60pM_18mW_1_MMStack_Pos3.ome.tif'),
        os.path.join('/', 'fs', 'mpib', 'pool-miblab1', 'users', 'schentarra', 'z_microscopy_raw', '260120_neurons#48_div16_GluA1-Fv-clasp_live', 'Cav2.1_ms_L6_160pM_18mW_1', 'Cav2.1_ms_L6_160pM_18mW_1_MMStack_Pos3.ome.tif'),
        os.path.join('/', 'fs', 'mpib', 'pool-miblab1', 'users', 'schentarra', 'z_microscopy_raw', '260120_neurons#48_div16_GluA1-Fv-clasp_live', 'PSD95_direct_R2_125pM_18mW_1', 'PSD95_direct_R2_125pM_18mW_1_MMStack_Pos3.ome.tif'),
        os.path.join('/', 'fs', 'mpib', 'pool-miblab1', 'users', 'schentarra', 'z_microscopy_raw', '260120_neurons#48_div16_GluA1-Fv-clasp_live', 'GluA1-scFv_Alfa_R3_125pM_18mW_1', 'GluA1-scFv_Alfa_R3_125pM_18mW_1_MMStack_Pos3.ome.tif'),
        os.path.join('/', 'fs', 'mpib', 'pool-miblab1', 'users', 'schentarra', 'z_microscopy_raw', '260120_neurons#48_div16_GluA1-Fv-clasp_live', 'Munc13_direct_R4_200pM_18mW_1', 'Munc13_direct_R4_200pM_18mW_1_MMStack_Pos3.ome.tif'),
    ],
}


# Single dataset workflow modules
workflow_modules_sgl = [
    (
        "load_picassoconfig",
        {
            "fp_config": os.path.join('/', 'fs', 'mpib', 'pool-miblab5', 'picasso-config', 'config_260127.yaml'),
        },
    ),
    (
        "load_dataset_movie",
        {
            "filename": ('$$map', 'filepath'),
            "sample_movie": {'filename': 'selected_frames.mp4', 'n_sample': 40, 'max_quantile': 0.9998, 'fps': 2.0},
            "load_camera_info": False,
        },
    ),
    (
        "identify",
        {
            "box_size": 7,
            "min_gradient": 20000.0,
            "auto_netgrad": {'box_size': 7, 'frame_numbers': 40, 'filename': 'auto-id.png', 'start_ng': -3000.0, 'zscore': 10.0, 'bins': 300},
            "ids_vs_frame": {'filename': ''},
        },
    ),
    (
        "localize",
        {
            "box_size": 7,
            "fit_parallel": True,
            "locs_vs_frame": {'filename': 'locsvsframe.png'},
        },
    ),
    (
        "zfit",
        {
            "magnification_factor": 0.79,
            "fp_calibration": '',
        },
    ),
    (
        "find_gold",
        {
            "nlocs_threshold": 100,
            "rms_threshold": 2.0,
            "frame_window": 100,
            "remove_gold": False,
            "diameter": 2.0,
        },
    ),
    (
        "undrift_from_picked",
        {
            "fp_picked_locs": ('$get_previous_module_result', 'fp_gold'),
            "interpolation_method": 'spline',
        },
    ),
    (
        "find_gold",
        {
            "nlocs_threshold": 100,
            "rms_threshold": 2.0,
            "frame_window": 100,
            "remove_gold": True,
            "diameter": 2.0,
        },
    ),
    (
        "filter_locs",
        {
            "field": 'ellipticity',
            "minval": 0,
            "maxval": '.9',
            "mode": 'absolute',
        },
    ),
    (
        "render",
        {
            "ctrmass_fov_nm": 20000.0,
            "fullfov_pixelsize": 130.0,
            "ctrmass_pixelsize": 50.0,
            "ctrmass_blur_method": 'gaussian',
            "ctrmass_min_blur_width": 1.0,
            "ctrmass_ang": 0.0,
        },
    ),
    (
        "save_single_dataset",
        {
            "filename": ('$$map', '#tags'),
        },
    ),
    (
        "summarize_dataset",
        {
            "include_plots": True,
            "methods": {'nena': ''},
        },
    ),
    (
        "dbscan",
        {
            "radius": ('$get_previous_module_result *3.0', 'nena, nena-nm'),
            "min_samples": 4,
            "min_locs": 0,
            "continue_with_centers": False,
        },
    ),
    (
        "gaussian_mixture_cluster",
        {
            "min_locs": 10,
            "max_rounds_without_best_bic": 3,
            "bootstrap_check": False,
            "calibration": ('$get_prior_result', 'results, 04_zfit, fp_calibration'),
            "loc_prec_handle": 'abs',
        },
    ),
    (
        "save_single_dataset",
        {
            "filename": ('$$map', '#tags'),
        },
    ),
]


# Aggregation workflow modules
workflow_modules_agg = [
    (
        "analysis_documentation",
        {
        },
    ),
    (
        "load_datasets_to_aggregate",
        {
            "filepaths": ('$$get_prior_result', 'all_results, single_dataset, $$all, 14_save_single_dataset, filepath'),
            "tags": ('$$map', '#tags'),
        },
    ),
    (
        "align_channels",
        {
            "filepaths": '',
            "fp_fiducials": ('$$get_prior_result', 'all_results, single_dataset, $$all, 07_find_gold, fp_gold'),
            "align_pars": {'max_iterations': 5, 'convergence': 0.001, 'force_method': 'RCC', 'max_shift': 50.0, 'plot_histogram': False, 'plot_dir': ''},
            "fig_filename": 'fig_align.png',
            "crop_boundaries": True,
            "fp_co_shift_channel_locs": '',
        },
    ),
    (
        "align_channels",
        {
            "filepaths": '',
            "fp_fiducials": ('$get_previous_module_result', 'fp_fiducials'),
            "align_pars": {'max_iterations': 5, 'convergence': 0.001, 'force_method': 'picked', 'max_shift': 4.0, 'plot_histogram': True, 'plot_dir': 'plots'},
            "fig_filename": 'fig_align.png',
            "crop_boundaries": True,
            "fp_co_shift_channel_locs": '',
        },
    ),
    (
        "render",
        {
            "filepaths": '',
            "fp_fiducials": ('$$get_prior_result', 'all_results, single_dataset, $$all, 07_find_gold, fp_gold'),
            "align_pars": {'max_iterations': 5, 'convergence': 0.001, 'force_method': 'RCC', 'max_shift': 50.0, 'plot_histogram': False, 'plot_dir': ''},
            "fig_filename": 'fig_align.png',
            "crop_boundaries": True,
            "fp_co_shift_channel_locs": '',
        },
    ),
    (
        "save_datasets_aggregated",
        {
            "filepaths": '',
            "fp_fiducials": ('$$get_prior_result', 'all_results, single_dataset, $$all, 07_find_gold, fp_gold'),
            "align_pars": {'max_iterations': 5, 'convergence': 0.001, 'force_method': 'RCC', 'max_shift': 50.0, 'plot_histogram': False, 'plot_dir': ''},
            "fig_filename": 'fig_align.png',
            "crop_boundaries": True,
            "fp_co_shift_channel_locs": '',
        },
    ),
]


if __name__ == "__main__":
    # Get working directory
    working_folder = os.path.dirname(os.path.abspath(__file__))
    src_loc_file = os.path.join(working_folder, 'src_loc.yaml')
    io.save_info(src_loc_file, [datasets])

    print('datasets', datasets)
    print('src_loc', src_loc_file)
    analysis_name = os.path.split(working_folder)[-1]

    # Create aggregation workflow coordinator
    coordinator = AggregationWorkflowCoordinator(
        src_loc_file, analysis_name, working_folder,
        confluence_url, confluence_space, confluence_token,
        base_page, dest_machine='hpcl8001',
        always_save=False
    )

    # Run analysis
    coordinator.run_analysis(workflow_modules_sgl, workflow_modules_agg)
