#!/usr/bin/env python
"""
Module Name: test_picasso_set.py
Author: Heinrich Grabmayr
Initial Date: October 5, 2026
Description: Test the picasso-set module layer: reconcile the registry
    entries against the mixin implementations, unit-test the analysis
    modules (picasso mocked), and exercise the generic reporter fallback.
"""

import logging
import os
import shutil
import tempfile
import unittest
from unittest.mock import MagicMock, patch

import numpy as np
import pandas as pd

from picasso_workflow import analyse, confluence, html_reporter
from picasso_workflow.modulespec import MODULE_REGISTRY
from picasso_workflow.picasso_set.params import (
    PICASSO_SET_PARAMS,
    PICASSO_SET_SUMMARIES,
    docstring,
)

logger = logging.getLogger(__name__)


def _picasso_set_names():
    """The registered picasso-set module names."""
    return {
        name
        for name, spec in MODULE_REGISTRY.items()
        if spec.module_set == "picasso"
    }


class TestPicassoSetReconciliation(unittest.TestCase):
    """Registry entries and mixin implementations must match 1:1."""

    def test_every_spec_is_implemented(self):
        for name in sorted(_picasso_set_names()):
            self.assertTrue(
                callable(getattr(analyse.AutoPicasso, name, None)),
                f"picasso-set spec {name} has no AutoPicasso implementation",
            )

    def test_every_implementation_has_a_spec(self):
        implemented = {
            name
            for name in dir(analyse.AutoPicasso)
            if name.startswith("picasso_")
            and callable(getattr(analyse.AutoPicasso, name))
        }
        orphan = implemented - _picasso_set_names()
        self.assertEqual(
            set(),
            orphan,
            f"picasso_* methods without a ModuleSpec: {sorted(orphan)}",
        )

    def test_params_and_summaries_complete(self):
        for name in sorted(_picasso_set_names()):
            self.assertIn(name, PICASSO_SET_PARAMS)
            self.assertIn(name, PICASSO_SET_SUMMARIES)
            self.assertTrue(docstring(name))

    def test_all_modules_have_unit_tests(self):
        """Every picasso-set module needs a test in TestPicassoSetModules."""
        missing = [
            name
            for name in sorted(_picasso_set_names())
            if not callable(
                getattr(TestPicassoSetModules, f"test_{name}", None)
            )
        ]
        if missing:
            raise NotImplementedError(
                f"Unit tests of picasso-set modules {missing} not implemented!"
            )


class TestPicassoSetModules(unittest.TestCase):
    """Unit tests of the picasso-set analysis modules (picasso mocked)."""

    def setUp(self):
        self.results_folder = tempfile.mkdtemp()
        analysis_config = {
            "camera_info": {
                "Gain": 1,
                "Sensitivity": 0.45,
                "Baseline": 100,
                "Qe": 0.82,
                "Pixelsize": 130,  # nm
            },
            "gpufit_installed": False,
        }
        self.ap = analyse.AutoPicasso(self.results_folder, analysis_config)
        locs_dtype = [
            ("frame", "u4"),
            ("x", "f4"),
            ("y", "f4"),
            ("photons", "f4"),
            ("lpx", "f4"),
            ("lpy", "f4"),
        ]
        self.ap.locs = pd.DataFrame(
            np.rec.array(
                [
                    tuple([i] + list(np.random.rand(len(locs_dtype) - 1)))
                    for i in range(10)
                ],
                dtype=locs_dtype,
            )
        )
        self.ap.info = [{"Width": 64, "Height": 32, "Frames": 1000}]

    def tearDown(self):
        shutil.rmtree(self.results_folder, ignore_errors=True)

    @patch(
        "picasso_workflow.picasso_set.analyse_core."
        "postprocess.compute_local_density"
    )
    def test_picasso_density(self, mock_cld):
        mock_cld.return_value = self.ap.locs
        with patch.object(self.ap, "_save_locs") as mock_save:
            parameters, results = self.ap.picasso_density(0, {"radius": 1.5})

        mock_cld.assert_called_once()
        self.assertEqual(1.5, mock_cld.call_args[0][2])
        self.assertTrue(results["success"])
        self.assertEqual(len(self.ap.locs), results["nlocs"])
        # saved like the CLI's _density.hdf5 output
        self.assertEqual(
            os.path.join(results["folder"], "locs_density.hdf5"),
            results["filepath_locs_density"],
        )
        mock_save.assert_any_call(results["filepath_locs_density"])
        # info entry mirrors the CLI
        self.assertIn("Density", self.ap.info[-1]["Generated by"])
        self.assertEqual(1.5, self.ap.info[-1]["Radius"])
        self.assertTrue(os.path.isdir(results["folder"]))


class TestPicassoSetGenericReporter(unittest.TestCase):
    """The generic reporter fallback serves every picasso-set module."""

    @patch("picasso_workflow.confluence.ConfluenceInterface")
    def setUp(self, mock_cfi):
        mock_instance = MagicMock()
        mock_instance.create_page.return_value = 534
        mock_instance.update_page_content.return_value = None
        mock_cfi.return_value = mock_instance
        self.cr = confluence.ConfluenceReporter(
            "url", "space", "parentpage", "my test report"
        )
        self.result_folder = tempfile.mkdtemp()

    def tearDown(self):
        shutil.rmtree(self.result_folder, ignore_errors=True)

    def _typical_results(self):
        fp_fig = os.path.join(self.result_folder, "plot.png")
        open(fp_fig, "w").close()
        fp_locs = os.path.join(self.result_folder, "locs_density.hdf5")
        open(fp_locs, "w").close()
        return {
            "folder": self.result_folder,
            "start time": "now",
            "end time": "later",
            "duration": 65.5,
            "nlocs": 1234,
            "filepath_locs_density": fp_locs,
        }

    def test_all_picasso_set_modules_resolve(self):
        for name in sorted(_picasso_set_names()):
            self.assertTrue(callable(getattr(self.cr, name)))

    def test_unknown_names_still_raise(self):
        with self.assertRaises(AttributeError):
            self.cr.not_a_module
        with self.assertRaises(AttributeError):
            self.cr._picasso_private_probe

    def test_generic_report_content(self):
        results = self._typical_results()
        text = self.cr.picasso_density(
            3, {"radius": 1.5}, results, postpone_report=True
        )
        self.assertIn("Module 03: picasso_density", text)
        self.assertIn("compute_local_density", text)
        self.assertIn("radius", text)
        # image embedded, non-image output listed
        self.assertIn("plot.png", text)
        self.assertIn("locs_density.hdf5", text)

    def test_generic_report_posts(self):
        results = self._typical_results()
        retval = self.cr.picasso_density(3, {"radius": 1.5}, results)
        self.assertIsNone(retval)
        self.cr.ci.upload_attachment.assert_called()
        self.cr.ci.update_page_content.assert_called()

    def test_generic_report_without_folder(self):
        # must not fail when the folder is gone (e.g. moved results)
        text = self.cr.picasso_density(
            1,
            {"radius": 1.5},
            {"folder": "/nonexistent", "duration": 1.0},
            postpone_report=True,
        )
        self.assertIn("Module 01: picasso_density", text)


class TestPicassoSetHtmlReporter(unittest.TestCase):
    """HTMLReporter inherits the generic picasso-set reporting."""

    def setUp(self):
        self.report_dir = tempfile.mkdtemp()
        self.hr = html_reporter.HTMLReporter(
            self.report_dir, "picasso set report"
        )

    def tearDown(self):
        shutil.rmtree(self.report_dir, ignore_errors=True)

    def test_generic_report_renders(self):
        result_folder = os.path.join(self.report_dir, "00_picasso_density")
        os.makedirs(result_folder)
        fp_fig = os.path.join(result_folder, "plot.png")
        open(fp_fig, "w").close()
        results = {
            "folder": result_folder,
            "duration": 3.0,
            "nlocs": 12,
        }
        self.hr.picasso_density(0, {"radius": 1.5}, results)
        report_file = self.hr.ci.html_path
        with open(report_file, encoding="utf-8") as f:
            content = f.read()
        self.assertIn("picasso_density", content)
        self.assertIn("plot.png", content)


if __name__ == "__main__":
    unittest.main()
