#!/usr/bin/env python
"""
Module Name: test_picasso_set.py
Author: Heinrich Grabmayr
Initial Date: October 5, 2026
Description: Test the picasso-set module layer: reconcile the registry
    entries against the mixin implementations, unit-test the analysis
    modules (picasso mocked), and exercise the generic reporter fallback.
"""

import logging
import os
import shutil
import tempfile
import unittest
from unittest.mock import MagicMock, patch

import numpy as np
import pandas as pd

from picasso_workflow import analyse, confluence, html_reporter
from picasso_workflow.modulespec import MODULE_REGISTRY
from picasso_workflow.picasso_set.params import (
    PICASSO_SET_PARAMS,
    PICASSO_SET_SUMMARIES,
    docstring,
)

logger = logging.getLogger(__name__)


def _picasso_set_names():
    """The registered picasso-set module names."""
    return {
        name
        for name, spec in MODULE_REGISTRY.items()
        if spec.module_set == "picasso"
    }


class TestPicassoSetReconciliation(unittest.TestCase):
    """Registry entries and mixin implementations must match 1:1."""

    def test_every_spec_is_implemented(self):
        for name in sorted(_picasso_set_names()):
            self.assertTrue(
                callable(getattr(analyse.AutoPicasso, name, None)),
                f"picasso-set spec {name} has no AutoPicasso implementation",
            )

    def test_every_implementation_has_a_spec(self):
        implemented = {
            name
            for name in dir(analyse.AutoPicasso)
            if name.startswith("picasso_")
            and callable(getattr(analyse.AutoPicasso, name))
        }
        orphan = implemented - _picasso_set_names()
        self.assertEqual(
            set(),
            orphan,
            f"picasso_* methods without a ModuleSpec: {sorted(orphan)}",
        )

    def test_params_and_summaries_complete(self):
        for name in sorted(_picasso_set_names()):
            self.assertIn(name, PICASSO_SET_PARAMS)
            self.assertIn(name, PICASSO_SET_SUMMARIES)
            self.assertTrue(docstring(name))

    def test_all_modules_have_unit_tests(self):
        """Every picasso-set module needs a test in TestPicassoSetModules."""
        missing = [
            name
            for name in sorted(_picasso_set_names())
            if not callable(
                getattr(TestPicassoSetModules, f"test_{name}", None)
            )
        ]
        if missing:
            raise NotImplementedError(
                f"Unit tests of picasso-set modules {missing} not implemented!"
            )


class TestPicassoSetModules(unittest.TestCase):
    """Unit tests of the picasso-set analysis modules (picasso mocked)."""

    def setUp(self):
        self.results_folder = tempfile.mkdtemp()
        analysis_config = {
            "camera_info": {
                "Gain": 1,
                "Sensitivity": 0.45,
                "Baseline": 100,
                "Qe": 0.82,
                "Pixelsize": 130,  # nm
            },
            "gpufit_installed": False,
        }
        self.ap = analyse.AutoPicasso(self.results_folder, analysis_config)
        locs_dtype = [
            ("frame", "u4"),
            ("x", "f4"),
            ("y", "f4"),
            ("photons", "f4"),
            ("lpx", "f4"),
            ("lpy", "f4"),
        ]
        self.ap.locs = pd.DataFrame(
            np.rec.array(
                [
                    tuple([i] + list(np.random.rand(len(locs_dtype) - 1)))
                    for i in range(10)
                ],
                dtype=locs_dtype,
            )
        )
        self.ap.info = [{"Width": 64, "Height": 32, "Frames": 1000}]

    def tearDown(self):
        shutil.rmtree(self.results_folder, ignore_errors=True)

    def _drift(self, n=5):
        return pd.DataFrame({"x": np.zeros(n), "y": np.zeros(n)})

    @patch("picasso_workflow.picasso_set.analyse_core.localize.localize")
    def test_picasso_localize(self, mock_localize):
        self.ap.movie = np.random.randint(
            0, 1000, size=(5, 32, 64), dtype=np.uint16
        )
        fit_info = {"Generated by": "Picasso Localize"}
        mock_localize.return_value = (
            self.ap.locs,
            self.ap.info + [fit_info],
        )
        with patch.object(self.ap, "_save_locs"):
            parameters, results = self.ap.picasso_localize(0, {})

        kwargs = mock_localize.call_args[1]
        # CLI defaults through the fit-method map
        self.assertEqual("gaussmle", kwargs["fitting_method"])
        self.assertEqual(
            5000,
            kwargs["identification_parameters"]["Min. Net Gradient"],
        )
        self.assertEqual(7, kwargs["identification_parameters"]["Box Size"])
        # convergence/max_iterations 0 -> the method's own defaults
        self.assertIsNone(kwargs["eps"])
        self.assertIsNone(kwargs["max_it"])
        # camera params default to the loaded camera config, not the
        # CLI literals (documented deviation)
        self.assertEqual(
            {
                "Baseline": 100,
                "Sensitivity": 0.45,
                "Gain": 1,
                "Qe": 0.82,
                "Pixelsize": 130,
            },
            kwargs["camera_info"],
        )
        self.assertEqual("Picasso Localize", self.ap.info[-1]["Generated by"])
        self.assertIn("filepath_locs", results)
        self.assertEqual(len(self.ap.locs), results["nlocs"])

    @patch("picasso_workflow.picasso_set.analyse_core.localize.localize")
    def test_picasso_localize_explicit_camera_params(self, mock_localize):
        self.ap.movie = np.zeros((2, 8, 8), dtype=np.uint16)
        mock_localize.return_value = (self.ap.locs, self.ap.info + [{}])
        with patch.object(self.ap, "_save_locs"):
            self.ap.picasso_localize(0, {"baseline": 200, "pixelsize": 108})
        cam = mock_localize.call_args[1]["camera_info"]
        self.assertEqual(200, cam["Baseline"])
        self.assertEqual(108, cam["Pixelsize"])
        # unset ones still come from the config
        self.assertEqual(0.45, cam["Sensitivity"])

    def test_picasso_localize_gpu_guard(self):
        with patch(
            "picasso_workflow.picasso_set.analyse_core."
            "localize.CUDA_AVAILABLE",
            False,
        ):
            with self.assertRaises(RuntimeError):
                self.ap.picasso_localize(0, {"fit_method": "mle-gpu"})

    def test_picasso_localize_spline_requires_calibration(self):
        with self.assertRaises(ValueError):
            self.ap.picasso_localize(0, {"fit_method": "spline"})

    def test_picasso_localize_3d_requires_zc_and_mf(self):
        with self.assertRaises(ValueError):
            self.ap.picasso_localize(0, {"fit_method": "lq-3d"})
        with self.assertRaises(ValueError):
            self.ap.picasso_localize(
                0, {"fit_method": "lq-3d", "zc": "cal.yaml"}
            )

    @patch("picasso_workflow.picasso_set.analyse_core.postprocess.plot_drift")
    @patch("picasso_workflow.picasso_set.analyse_core.io.save_drift")
    @patch("picasso_workflow.picasso_set.analyse_core.postprocess.undrift")
    def test_picasso_undrift_rcc(self, mock_undrift, mock_sd, mock_pd):
        drift = self._drift()
        mock_undrift.return_value = (drift, self.ap.locs)
        with patch.object(self.ap, "_save_locs"):
            parameters, results = self.ap.picasso_undrift_rcc(
                0, {"segmentation": 500}
            )
        self.assertEqual(500, mock_undrift.call_args[0][2])
        self.assertIs(self.ap.drift, drift)
        mock_sd.assert_called_once()
        self.assertIn("filepath_driftfile", results)
        self.assertIn("filepath_locs_undrift", results)
        entry = self.ap.info[-1]
        self.assertIn("Undrift", entry["Generated by"])
        self.assertEqual(500, entry["Segmentation"])

    @patch("picasso_workflow.picasso_set.analyse_core.postprocess.plot_drift")
    @patch("picasso_workflow.picasso_set.analyse_core.io.save_drift")
    @patch("picasso_workflow.picasso_set.analyse_core.aim.aim")
    def test_picasso_undrift_aim(self, mock_aim, mock_sd, mock_pd):
        drift = self._drift()
        new_info = self.ap.info + [{"Generated by": "Picasso AIM"}]
        mock_aim.return_value = (self.ap.locs, new_info, drift)
        with patch.object(self.ap, "_save_locs"):
            parameters, results = self.ap.picasso_undrift_aim(0, {})
        # CLI defaults
        args = mock_aim.call_args[0]
        self.assertEqual(100, args[2])
        self.assertAlmostEqual(20 / 130, args[3])
        self.assertAlmostEqual(60 / 130, args[4])
        self.assertIs(self.ap.drift, drift)
        self.assertIn("filepath_locs_aim", results)

    @patch("picasso_workflow.picasso_set.analyse_core.postprocess.plot_drift")
    @patch("picasso_workflow.picasso_set.analyse_core.io.save_drift")
    @patch(
        "picasso_workflow.picasso_set.analyse_core."
        "postprocess.undrift_from_fiducials"
    )
    @patch("picasso_workflow.picasso_set.analyse_core.postprocess.undrift")
    def test_picasso_undrift_fiducials(
        self, mock_undrift, mock_uff, mock_sd, mock_pd
    ):
        drift = self._drift()
        mock_undrift.return_value = (drift, self.ap.locs)
        new_info = self.ap.info + [
            {"Number of picks": 7, "Pick radius (nm)": 500.0}
        ]
        mock_uff.return_value = (self.ap.locs, new_info, drift)
        with patch.object(self.ap, "_save_locs"):
            parameters, results = self.ap.picasso_undrift_fiducials(0, {})
        # CLI composite: pre-RCC with segmentation 2000
        self.assertEqual(2000, mock_undrift.call_args[0][2])
        entry = self.ap.info[-1]
        self.assertEqual(7, entry["Number of picks"])
        self.assertEqual(2000, entry["pre-RCC segmentation"])
        self.assertIn("filepath_locs_undrift_fiducials", results)

    @patch("picasso_workflow.picasso_set.analyse_core.postprocess.link")
    def test_picasso_link(self, mock_link):
        mock_link.return_value = self.ap.locs
        with patch.object(self.ap, "_save_locs"):
            parameters, results = self.ap.picasso_link(0, {})
        # CLI defaults
        self.assertEqual(1.0, mock_link.call_args[0][2])
        self.assertEqual(1, mock_link.call_args[0][3])
        entry = self.ap.info[-1]
        self.assertEqual(1.0, entry["Maximum Distance"])
        self.assertEqual(1, entry["Maximum Transient Dark Time"])
        self.assertIn("filepath_locs_link", results)

    @patch(
        "picasso_workflow.picasso_set.analyse_core."
        "postprocess.compute_dark_times"
    )
    def test_picasso_dark(self, mock_dark):
        mock_dark.return_value = self.ap.locs
        with patch.object(self.ap, "_save_locs"):
            parameters, results = self.ap.picasso_dark(0, {})
        mock_dark.assert_called_once()
        self.assertIn("Dark", self.ap.info[-1]["Generated by"])
        self.assertIn("filepath_locs_dark", results)

    @patch("picasso_workflow.picasso_set.analyse_core.io.save_datasets")
    @patch("picasso_workflow.picasso_set.analyse_core.postprocess.groupprops")
    def test_picasso_groupprops(self, mock_gp, mock_sd):
        groups = pd.DataFrame({"group": [0, 1], "n_events": [3, 5]})
        mock_gp.return_value = groups
        parameters, results = self.ap.picasso_groupprops(0, {})
        mock_sd.assert_called_once()
        self.assertEqual(2, results["n_groups"])
        self.assertIn("filepath_locs_groupprops", results)

    @patch(
        "picasso_workflow.picasso_set.analyse_core."
        "postprocess.pair_correlation"
    )
    def test_picasso_pair_correlation(self, mock_pc):
        bins = np.linspace(0.1, 10, 100)
        mock_pc.return_value = (bins, np.random.rand(100))
        parameters, results = self.ap.picasso_pair_correlation(0, {})
        # CLI defaults
        self.assertEqual(0.1, mock_pc.call_args[0][2])
        self.assertEqual(10, mock_pc.call_args[0][3])
        self.assertTrue(os.path.isfile(results["fp_fig_pair_correlation"]))
        self.assertTrue(os.path.isfile(results["filepath_pair_correlation"]))

    @patch("picasso_workflow.picasso_set.analyse_core.io.save_locs")
    @patch(
        "picasso_workflow.picasso_set.analyse_core."
        "clusterer.find_cluster_centers"
    )
    @patch("picasso_workflow.picasso_set.analyse_core.clusterer.dbscan")
    def test_picasso_dbscan(self, mock_dbscan, mock_fcc, mock_sl):
        mock_dbscan.return_value = (self.ap.locs, {"Generated by": "DBSCAN"})
        mock_fcc.return_value = self.ap.locs.iloc[:3]
        with patch.object(self.ap, "_save_locs"):
            parameters, results = self.ap.picasso_dbscan(
                0, {"radius": 0.5, "density": 4}
            )
        args = mock_dbscan.call_args
        self.assertEqual(0.5, args[0][1])
        self.assertEqual(4, args[0][2])
        self.assertEqual(3, results["nclusters"])
        self.assertIn("filepath_locs_dbclusters", results)

    @patch("picasso_workflow.picasso_set.analyse_core.io.save_locs")
    @patch(
        "picasso_workflow.picasso_set.analyse_core."
        "clusterer.find_cluster_centers"
    )
    @patch("picasso_workflow.picasso_set.analyse_core.clusterer.hdbscan")
    def test_picasso_hdbscan(self, mock_hdbscan, mock_fcc, mock_sl):
        mock_hdbscan.return_value = (
            self.ap.locs,
            {"Generated by": "HDBSCAN"},
        )
        mock_fcc.return_value = self.ap.locs.iloc[:2]
        with patch.object(self.ap, "_save_locs"):
            parameters, results = self.ap.picasso_hdbscan(
                0, {"min_cluster": 10, "min_samples": 5}
            )
        args = mock_hdbscan.call_args[0]
        self.assertEqual(10, args[1])
        self.assertEqual(5, args[2])
        self.assertEqual(2, results["nclusters"])
        self.assertIn("filepath_locs_hdbclusters", results)

    @patch("picasso_workflow.picasso_set.analyse_core.io.save_locs")
    @patch(
        "picasso_workflow.picasso_set.analyse_core."
        "clusterer.find_cluster_centers"
    )
    @patch("picasso_workflow.picasso_set.analyse_core.clusterer.cluster")
    def test_picasso_smlm_cluster(self, mock_cluster, mock_fcc, mock_sl):
        mock_cluster.return_value = (self.ap.locs, {"Generated by": "SMLM"})
        mock_fcc.return_value = self.ap.locs.iloc[:4]
        with patch.object(self.ap, "_save_locs"):
            parameters, results = self.ap.picasso_smlm_cluster(
                0, {"radius": 0.3, "min_locs": 8}
            )
        kwargs = mock_cluster.call_args[1]
        self.assertEqual(0.3, kwargs["radius_xy"])
        self.assertEqual(8, kwargs["min_locs"])
        self.assertFalse(kwargs["frame_analysis"])  # CLI default basic_fa
        self.assertEqual(4, results["nclusters"])
        self.assertIn("filepath_locs_cluster_centers", results)

    @patch("picasso_workflow.picasso_set.analyse_core.pd.read_hdf")
    def test_picasso_nneighbor(self, mock_read_hdf):
        mock_read_hdf.return_value = pd.DataFrame(
            {
                "com_x": [0.0, 1.0, 5.0],
                "com_y": [0.0, 0.0, 0.0],
            }
        )
        parameters, results = self.ap.picasso_nneighbor(
            0, {"files": "clusters.hdf5"}
        )
        self.assertEqual(3, results["n_points"])
        self.assertTrue(os.path.isfile(results["filepath_minval"]))
        minvals = np.loadtxt(results["filepath_minval"])
        np.testing.assert_allclose(minvals, [1.0, 1.0, 4.0])

    @patch("picasso_workflow.picasso_set.analyse_core.io.save_locs")
    @patch("picasso_workflow.picasso_set.analyse_core.io.load_clusters")
    def test_picasso_clusterfilter(self, mock_lc, mock_sl):
        self.ap.locs["group"] = [0, 0, 1, 1, 2, 2, 3, 3, 4, 4]
        mock_lc.return_value = pd.DataFrame(
            {
                "groups": [0, 1, 2, 3, 4],
                "n_events": [1.0, 5.0, 5.0, 5.0, 9.0],
            }
        )
        parameters, results = self.ap.picasso_clusterfilter(
            0,
            {
                "clusterfile": "clusters.hdf5",
                "parameter": "n_events",
                "minval": 2.0,
                "maxval": 8.0,
            },
        )
        self.assertEqual(6, results["nlocs_in"])
        self.assertEqual(4, results["nlocs_out"])
        # workflow continues with the in-range locs
        self.assertEqual(6, len(self.ap.locs))
        self.assertIn("Clusterfilter - in", self.ap.info[-1]["Generated by"])

    @patch("picasso_workflow.picasso_set.analyse_core.io.load_clusters")
    def test_picasso_clusterfilter_aborts_on_empty_range(self, mock_lc):
        self.ap.locs["group"] = np.zeros(len(self.ap.locs), dtype=int)
        mock_lc.return_value = pd.DataFrame({"groups": [0], "n_events": [1.0]})
        parameters, results = self.ap.picasso_clusterfilter(
            0,
            {
                "clusterfile": "clusters.hdf5",
                "parameter": "n_events",
                "minval": 2.0,
                "maxval": 8.0,
            },
        )
        self.assertFalse(results["success"])

    @patch(
        "picasso_workflow.picasso_set.analyse_core."
        "postprocess.cluster_combine"
    )
    def test_picasso_cluster_combine(self, mock_cc):
        mock_cc.return_value = self.ap.locs
        with patch.object(self.ap, "_save_locs"):
            parameters, results = self.ap.picasso_cluster_combine(0, {})
        mock_cc.assert_called_once()
        self.assertIn("Combine", self.ap.info[-1]["Generated by"])
        self.assertIn("filepath_locs_comb", results)

    @patch(
        "picasso_workflow.picasso_set.analyse_core."
        "postprocess.cluster_combine_dist"
    )
    def test_picasso_cluster_combine_dist(self, mock_ccd):
        self.ap.info.append({"Pixelsize": 130})
        mock_ccd.return_value = self.ap.locs
        with patch.object(self.ap, "_save_locs"):
            parameters, results = self.ap.picasso_cluster_combine_dist(0, {})
        # pixelsize read from metadata like the CLI
        self.assertEqual(130, mock_ccd.call_args[0][1])
        self.assertIn("CombineDist", self.ap.info[-1]["Generated by"])

    @patch("picasso_workflow.picasso_set.analyse_core.g5m.g5m")
    def test_picasso_g5m(self, mock_g5m):
        mols = self.ap.locs.iloc[:3]
        g5m_info = self.ap.info + [{"Generated by": "Picasso G5M"}]
        mock_g5m.return_value = (mols, None, g5m_info)
        with patch.object(self.ap, "_save_locs"):
            parameters, results = self.ap.picasso_g5m(0, {})
        kwargs = mock_g5m.call_args[1]
        # CLI defaults
        self.assertEqual(10, kwargs["min_locs"])
        self.assertEqual("local", kwargs["loc_prec_handle"])
        self.assertEqual((0.8, 1.5), kwargs["sigma_bounds"])
        self.assertEqual(3, kwargs["max_rounds_without_best_bic"])
        self.assertTrue(kwargs["postprocess"])
        self.assertEqual("group", kwargs["group_column"])
        self.assertIsNone(kwargs["calibration"])
        self.assertEqual(3, results["n_molecules"])
        self.assertIs(self.ap.locs, mols)
        self.assertIn("filepath_locs_molmap", results)

    def test_picasso_g5m_3d_astigmatism_requires_calibration(self):
        self.ap.locs["z"] = np.zeros(len(self.ap.locs))
        with self.assertRaises(ValueError):
            self.ap.picasso_g5m(0, {})

    @patch("picasso_workflow.picasso_set.analyse_core.render.render")
    def test_picasso_render(self, mock_render):
        mock_render.return_value = (len(self.ap.locs), np.random.rand(32, 64))
        parameters, results = self.ap.picasso_render(0, {})
        kwargs = mock_render.call_args[1]
        # CLI defaults
        self.assertEqual(10.0, kwargs["disp_px_size"])
        self.assertEqual("convolve", kwargs["blur_method"])
        self.assertTrue(os.path.isfile(results["fp_fig_render"]))
        self.assertEqual(len(self.ap.locs), results["n_rendered"])

    @patch("picasso_workflow.picasso_set.analyse_core.render.render")
    def test_picasso_render_blur_none(self, mock_render):
        mock_render.return_value = (0, np.random.rand(8, 8))
        self.ap.picasso_render(0, {"blur_method": "none"})
        self.assertIsNone(mock_render.call_args[1]["blur_method"])

    @patch("picasso_workflow.picasso_set.analyse_core.io.save_locs")
    @patch("picasso_workflow.picasso_set.analyse_core.postprocess.align")
    @patch("picasso_workflow.picasso_set.analyse_core.io.load_locs")
    def test_picasso_align(self, mock_ll, mock_align, mock_sl):
        mock_ll.return_value = (self.ap.locs, [{"Frames": 1000}])
        mock_align.return_value = [self.ap.locs, self.ap.locs]
        parameters, results = self.ap.picasso_align(
            0, {"files": ["a.hdf5", "b.hdf5"]}
        )
        self.assertEqual(2, len(results["filepaths_aligned"]))
        self.assertTrue(
            results["filepaths_aligned"][0].endswith("a_align.hdf5")
        )
        self.assertEqual(2, mock_sl.call_count)

    @patch("picasso_workflow.picasso_set.analyse_core.lib.merge_locs")
    @patch("picasso_workflow.picasso_set.analyse_core.io.load_locs")
    def test_picasso_join(self, mock_ll, mock_merge):
        mock_ll.return_value = (self.ap.locs, [{"Frames": 10}])
        mock_merge.return_value = self.ap.locs
        with patch.object(self.ap, "_save_locs"):
            parameters, results = self.ap.picasso_join(
                0, {"files": ["a.hdf5", "b.hdf5"]}
            )
        # frames reindexed by default (CLI keepindex defaults to off)
        self.assertTrue(mock_merge.call_args[1]["increment_frames"])
        self.assertEqual(
            int(self.ap.locs["frame"].max()) + 1, self.ap.info[0]["Frames"]
        )
        self.assertIn("Join", self.ap.info[-1]["Generated by"])
        self.assertIn("filepath_locs_join", results)

    # --- review-fix regressions ---------------------------------------

    @patch("picasso_workflow.picasso_set.analyse_core.localize.localize")
    def test_picasso_localize_camera_info_from_property(self, mock_localize):
        """Camera params resolve via the camera_info property (config /
        picasso CONFIG), not only the raw analysis_config dict."""
        self.ap.movie = np.zeros((2, 8, 8), dtype=np.uint16)
        mock_localize.return_value = (self.ap.locs, self.ap.info + [{}])
        with patch.object(
            type(self.ap),
            "camera_info",
            new_callable=lambda: property(
                lambda s: {"Baseline": 50, "Sensitivity": 2.0}
            ),
        ):
            with patch.object(self.ap, "_save_locs"):
                self.ap.picasso_localize(0, {})
        cam = mock_localize.call_args[1]["camera_info"]
        self.assertEqual(50, cam["Baseline"])
        self.assertEqual(2.0, cam["Sensitivity"])
        # keys the property does not carry fall back to the CLI literals
        self.assertEqual(1, cam["Gain"])

    @patch("picasso_workflow.picasso_set.analyse_core.localize.localize")
    def test_picasso_localize_explicit_none_camera_info(self, mock_localize):
        """An explicit camera_info: None in the analysis config (as the
        generated start_workflow templates write it) must not crash
        (regression: cluster run 6065761, 'NoneType' has no attribute
        'get') but resolve like an absent entry."""
        self.ap.analysis_config = {
            "camera_info": None,
            "gpufit_installed": False,
        }
        self.ap.movie = np.zeros((2, 8, 8), dtype=np.uint16)
        mock_localize.return_value = (self.ap.locs, self.ap.info + [{}])
        with patch.object(self.ap, "_save_locs"):
            self.ap.picasso_localize(0, {})
        cam = mock_localize.call_args[1]["camera_info"]
        self.assertEqual(0, cam["Baseline"])
        self.assertEqual(130, cam["Pixelsize"])

    @patch("picasso_workflow.picasso_set.analyse_core.localize.localize")
    def test_picasso_localize_camera_info_property_failure(
        self, mock_localize
    ):
        """An unresolvable camera_info property falls back gracefully."""
        self.ap.analysis_config = {"gpufit_installed": False}
        self.ap.movie = np.zeros((2, 8, 8), dtype=np.uint16)
        mock_localize.return_value = (self.ap.locs, self.ap.info + [{}])
        with patch.object(self.ap, "_save_locs"):
            self.ap.picasso_localize(0, {})
        cam = mock_localize.call_args[1]["camera_info"]
        # CLI literals as last resort
        self.assertEqual(0, cam["Baseline"])
        self.assertEqual(130, cam["Pixelsize"])

    def test_square_picks_round_trip(self):
        """Square pick sizes survive a save/load round trip in camera px."""
        from picasso import io as picasso_io

        self.ap.info.append({"Pixelsize": 130})
        results = {"folder": self.results_folder}
        fp = self.ap._picasso_set_save_picks(
            results, [[1.0, 2.0]], "Square", 5.0, "picks.yaml"
        )
        picks, shape, size = picasso_io.load_picks(fp, pixelsize=130)
        self.assertEqual("Square", shape)
        self.assertAlmostEqual(5.0, size)

    @patch(
        "picasso_workflow.picasso_set.analyse_core."
        "postprocess.compute_dark_times"
    )
    def test_save_locs_registers_checkpoint_once(self, mock_dark):
        """The module save doubles as the resume checkpoint: with
        always_save, the decorator must not write a second copy."""
        mock_dark.return_value = self.ap.locs
        self.ap.analysis_config["always_save"] = True
        with patch.object(self.ap, "_save_locs") as mock_save:
            parameters, results = self.ap.picasso_dark(0, {})
        self.assertEqual(1, mock_save.call_count)
        self.assertEqual(
            results["filepath_locs_dark"],
            results["checkpoint"]["single"]["filepath"],
        )

    @patch("picasso.masking.mask_locs")
    @patch("picasso.masking.mask_image")
    @patch("picasso.masking.generate_image")
    def test_picasso_mask_locs_numeric_threshold(
        self, mock_gi, mock_mi, mock_ml
    ):
        """An explicit threshold entered as text reaches mask_image as a
        float."""
        mock_gi.return_value = np.random.rand(8, 8)
        mock_mi.return_value = (np.ones((8, 8), dtype=bool), 0.5)
        mock_ml.return_value = (self.ap.locs, self.ap.locs.iloc[:0])
        with patch.object(self.ap, "_save_locs"):
            self.ap.picasso_mask_locs(
                0, {"disp_px_size": 100.0, "blur": 2.0, "method": "0.5"}
            )
        self.assertEqual(0.5, mock_mi.call_args[0][1])

    def test_doubled_sign_command_fallback_and_error(self):
        """A per-channel '$$' command in a single-dataset run resolves to
        its spec default, or fails with an actionable message."""
        from picasso_workflow.util import ParameterCommandExecutor

        pce = ParameterCommandExecutor(None)
        resolved = pce.run({"filename": ("$$map", "#tags", None)})
        self.assertIsNone(resolved["filename"])
        resolved = pce.run({"min_locs": ("$$map", "min_locs", 10)})
        self.assertEqual(10, resolved["min_locs"])
        with self.assertRaises(ValueError) as ctx:
            pce.run({"filename": ("$$map", "filepath")})
        self.assertIn("aggregation", str(ctx.exception))

    # --- tier 3: calibration & 3D -------------------------------------

    @patch(
        "picasso_workflow.picasso_set.analyse_calibration."
        "io.load_calibration"
    )
    @patch("picasso.zfit.zfit")
    def test_picasso_zfit(self, mock_zfit, mock_lc):
        mock_lc.return_value = {"X Coefficients": [1]}
        mock_zfit.return_value = (self.ap.locs, self.ap.info + [{}])
        with patch.object(self.ap, "_save_locs"):
            parameters, results = self.ap.picasso_zfit(
                0, {"calibration": "zcal.yaml"}
            )
        kwargs = mock_zfit.call_args[1]
        # library defaults
        self.assertEqual("gausslq", kwargs["fitting_method"])
        self.assertEqual(2, kwargs["filter"])
        self.assertFalse(kwargs["gpu"])
        self.assertEqual("zcal.yaml", self.ap.info[-1]["Z Calibration Path"])
        self.assertIn("filepath_locs_zfit", results)

    @patch(
        "picasso_workflow.picasso_set.analyse_calibration."
        "io.load_calibration"
    )
    @patch("picasso.zfit.zfit")
    def test_picasso_zfit_failure(self, mock_zfit, mock_lc):
        mock_lc.return_value = {}
        mock_zfit.return_value = (None, None)
        parameters, results = self.ap.picasso_zfit(
            0, {"calibration": "zcal.yaml"}
        )
        self.assertFalse(results["success"])

    @patch(
        "picasso_workflow.picasso_set.analyse_calibration."
        "io.save_calibration"
    )
    @patch("picasso.zfit.calibrate_z")
    def test_picasso_calibrate_z(self, mock_cz, mock_sc):
        mock_cz.return_value = {"Number of frames": 100}
        parameters, results = self.ap.picasso_calibrate_z(
            0, {"d": 10.0, "magnification_factor": 0.79}
        )
        args = mock_cz.call_args
        self.assertEqual(10.0, args[0][2])
        self.assertEqual(0.79, args[0][3])
        # library defaults
        self.assertEqual(1, args[1]["frames_per_step"])
        self.assertEqual("fov", args[1]["frame_order"])
        self.assertTrue(
            results["filepath_z_calibration"].endswith("z_calibration.yaml")
        )
        self.assertEqual(100, results["num_frames"])

    @patch(
        "picasso_workflow.picasso_set.analyse_calibration."
        "io.save_camera_calibration"
    )
    @patch("picasso.scmos.calibrate_scmos")
    @patch("picasso_workflow.picasso_set.analyse_calibration.io.load_movie")
    def test_picasso_camera_calibrate(self, mock_lm, mock_cal, mock_scc):
        mock_lm.return_value = (np.zeros((10, 8, 8)), [{}])
        mock_cal.return_value = {
            "Frames": 10,
            "Offset median (ADU)": 100.0,
            "Variance median (ADU^2)": 4.0,
            "Hot pixels": 3,
            "gain": None,
        }
        parameters, results = self.ap.picasso_camera_calibrate(
            0, {"dark": "dark.tif"}
        )
        # CLI default power unit; no light movies -> bright None
        self.assertIsNone(mock_cal.call_args[0][1])
        self.assertEqual("mW", mock_cal.call_args[1]["level_unit"])
        mock_scc.assert_called_once()
        self.assertEqual(3, results["hot_pixels"])
        self.assertIn("filepath_camera_calibration", results)

    def test_picasso_camera_calibrate_power_mismatch(self):
        with self.assertRaises(ValueError):
            self.ap.picasso_camera_calibrate(
                0,
                {
                    "dark": "dark.tif",
                    "light": ["a.tif"],
                    "power": [1.0, 2.0],
                },
            )

    @patch("picasso.scmos.validate_calibration")
    @patch("picasso_workflow.picasso_set.analyse_calibration.io.load_movie")
    @patch(
        "picasso_workflow.picasso_set.analyse_calibration."
        "io.load_camera_calibration"
    )
    def test_picasso_camera_validate(self, mock_lcc, mock_lm, mock_val):
        mock_lcc.return_value = {"offset": None}
        mock_lm.return_value = (np.zeros((10, 8, 8)), [{}])
        mock_val.return_value = {
            "valid": True,
            "Frames": 1000,
            "Pixels tested": 4096,
            "mean p-value": 0.51,
            "fraction p < 0.05": 0.05,
            "fraction p > 0.95": 0.04,
        }
        parameters, results = self.ap.picasso_camera_validate(
            0, {"calibration": "cal.hdf5", "movie": "dark.tif"}
        )
        self.assertTrue(results["valid"])
        self.assertAlmostEqual(0.51, results["mean_p_value"])

    @patch("picasso.spline.calibrate_spline")
    @patch("picasso_workflow.picasso_set.analyse_calibration.io.load_movie")
    def test_picasso_spline_calibrate(self, mock_lm, mock_cs):
        mock_lm.return_value = (np.zeros((10, 8, 8)), [{}])
        mock_cs.return_value = {"model": "spline-3d"}
        parameters, results = self.ap.picasso_spline_calibrate(
            0, {"files": ["beads.tif"], "step": 10.0}
        )
        kwargs = mock_cs.call_args[1]
        # CLI defaults
        self.assertEqual(13, kwargs["box"])
        self.assertEqual(5000, kwargs["minimum_ng"])
        self.assertEqual(10.0, kwargs["d"])
        self.assertEqual("spline-3d", kwargs["model"])
        self.assertEqual(0.79, kwargs["magnification_factor"])
        self.assertEqual(
            {
                "Baseline": 0,
                "Sensitivity": 1,
                "Gain": 1,
                "Pixelsize": 130,
            },
            kwargs["camera_info"],
        )
        self.assertIn("filepath_spline_calibration", results)
        self.assertEqual("spline-3d", results["spline_model"])

    @patch(
        "picasso_workflow.picasso_set.analyse_calibration."
        "io.save_any_calibration"
    )
    @patch(
        "picasso_workflow.picasso_set.analyse_calibration."
        "localize.plot_lateral_calibration"
    )
    @patch(
        "picasso_workflow.picasso_set.analyse_calibration."
        "localize.fit_lateral_transform"
    )
    @patch("picasso_workflow.picasso_set.analyse_calibration.io.load_movie")
    def test_picasso_lateral_calibrate(
        self, mock_lm, mock_flt, mock_plot, mock_sac
    ):
        mock_lm.return_value = (np.zeros((10, 8, 8)), [{}])
        mock_flt.return_value = ({"transforms": []}, {"n_pairs": 12})
        parameters, results = self.ap.picasso_lateral_calibrate(
            0, {"reference": "ref.tif", "target": "target.tif"}
        )
        kwargs = mock_flt.call_args[1]
        # CLI defaults
        self.assertEqual(7, kwargs["box"])
        self.assertEqual(5000, kwargs["minimum_ng"])
        self.assertEqual("astigmatism", kwargs["transform_type"])
        self.assertEqual("affine", kwargs["model"])
        self.assertEqual(12, results["n_bead_pairs"])
        self.assertTrue(
            results["filepath_lateral_calibration"].endswith(
                "lateral_calib.yaml"
            )
        )
        mock_plot.assert_called_once()
        mock_sac.assert_called_once()

    # --- tier 4: format converters --------------------------------------

    @patch("picasso_workflow.picasso_set.analyse_io.io.import_ts")
    def test_picasso_csv2hdf(self, mock_its):
        mock_its.return_value = (self.ap.locs, [{"Frames": 10}])
        parameters, results = self.ap.picasso_csv2hdf(
            0, {"files": "/data/ts.csv", "pixelsize": 130}
        )
        mock_its.assert_called_once_with("/data/ts.csv", 130)
        # import_ts writes <base>_locs.hdf5 next to the input (CLI)
        self.assertEqual("/data/ts_locs.hdf5", results["filepath_converted"])
        self.assertEqual([{"Frames": 10}], self.ap.info)

    @patch("picasso_workflow.picasso_set.analyse_io.io.save_locs")
    @patch("picasso_workflow.picasso_set.analyse_io.io.import_smap")
    def test_picasso_smap2hdf(self, mock_ism, mock_sl):
        mock_ism.return_value = (self.ap.locs, [{"Frames": 10}])
        parameters, results = self.ap.picasso_smap2hdf(
            0, {"files": "/data/x_sml.mat", "pixelsize": 130}
        )
        self.assertEqual(
            "/data/x_sml_locs.hdf5", results["filepath_converted"]
        )
        mock_sl.assert_called_once()

    def _assert_export(self, module, suffix, results):
        self.assertTrue(
            results["filepath_converted"].endswith("locs" + suffix),
            f"{module}: unexpected output {results['filepath_converted']}",
        )
        self.assertEqual(len(self.ap.locs), results["nlocs"])

    def test_picasso_hdf2csv(self):
        parameters, results = self.ap.picasso_hdf2csv(0, {})
        self._assert_export("picasso_hdf2csv", ".csv", results)
        self.assertTrue(os.path.isfile(results["filepath_converted"]))

    @patch("picasso_workflow.picasso_set.analyse_io.io.export_thunderstorm")
    def test_picasso_hdf2ts(self, mock_exp):
        parameters, results = self.ap.picasso_hdf2ts(0, {})
        self._assert_export("picasso_hdf2ts", ".csv", results)
        mock_exp.assert_called_once()

    @patch("picasso_workflow.picasso_set.analyse_io.io.export_txt_imagej")
    def test_picasso_hdf2imagej(self, mock_exp):
        parameters, results = self.ap.picasso_hdf2imagej(0, {})
        self._assert_export("picasso_hdf2imagej", ".txt", results)
        mock_exp.assert_called_once()

    @patch("picasso_workflow.picasso_set.analyse_io.io.export_txt_nis")
    def test_picasso_hdf2nis(self, mock_exp):
        parameters, results = self.ap.picasso_hdf2nis(0, {})
        self._assert_export("picasso_hdf2nis", ".nis.txt", results)
        mock_exp.assert_called_once()

    @patch("picasso_workflow.picasso_set.analyse_io.io.export_xyz_chimera")
    def test_picasso_hdf2chimera(self, mock_exp):
        parameters, results = self.ap.picasso_hdf2chimera(0, {})
        self._assert_export("picasso_hdf2chimera", ".chi.xyz", results)
        mock_exp.assert_called_once()

    @patch("picasso_workflow.picasso_set.analyse_io.io.export_3d_visp")
    def test_picasso_hdf2visp(self, mock_exp):
        parameters, results = self.ap.picasso_hdf2visp(0, {})
        self._assert_export("picasso_hdf2visp", ".visp.3d", results)
        mock_exp.assert_called_once()

    @patch("picasso_workflow.picasso_set.analyse_io.io.export_smap")
    def test_picasso_hdf2smap(self, mock_exp):
        parameters, results = self.ap.picasso_hdf2smap(0, {})
        self._assert_export("picasso_hdf2smap", "_sml.mat", results)
        mock_exp.assert_called_once()

    @patch("picasso_workflow.picasso_set.analyse_io.io.export_smap")
    @patch("picasso_workflow.picasso_set.analyse_io.io.load_locs")
    def test_picasso_export_explicit_file(self, mock_ll, mock_exp):
        """Exporters accept an explicit files path instead (CLI parity)."""
        mock_ll.return_value = (self.ap.locs, [{}])
        parameters, results = self.ap.picasso_hdf2smap(
            0, {"files": "/data/other_locs.hdf5"}
        )
        self.assertTrue(
            results["filepath_converted"].endswith("other_locs_sml.mat")
        )

    # --- tier 2: picks/postprocessing ---------------------------------

    _PICKS = ([[1.0, 2.0], [3.0, 4.0]], "Circle", 1.5)

    @patch(
        "picasso_workflow.picasso_set.analyse_picks." "postprocess.picked_locs"
    )
    @patch("picasso_workflow.picasso_set.analyse_picks.io.load_picks")
    def test_picasso_picked_locs(self, mock_lp, mock_pl):
        mock_lp.return_value = self._PICKS
        mock_pl.return_value = [self.ap.locs.iloc[:3], self.ap.locs.iloc[3:6]]
        with patch.object(self.ap, "_save_locs"):
            parameters, results = self.ap.picasso_picked_locs(
                0, {"picks_file": "picks.yaml"}
            )
        self.assertEqual(2, results["n_picks"])
        self.assertEqual(6, results["nlocs"])
        self.assertEqual(6, len(self.ap.locs))
        self.assertIn("Pick", self.ap.info[-1]["Generated by"])
        self.assertTrue(mock_pl.call_args[1]["add_group"])

    @patch(
        "picasso_workflow.picasso_set.analyse_picks."
        "postprocess.pick_similar"
    )
    @patch("picasso_workflow.picasso_set.analyse_picks.io.load_picks")
    def test_picasso_pick_similar(self, mock_lp, mock_ps):
        import yaml as _yaml

        mock_lp.return_value = self._PICKS
        mock_ps.return_value = [[1.0, 2.0], [3.0, 4.0], [5.0, 6.0]]
        parameters, results = self.ap.picasso_pick_similar(
            0, {"picks_file": "picks.yaml"}
        )
        self.assertEqual(2.0, mock_ps.call_args[1]["std_range"])
        self.assertEqual(2, results["n_picks_input"])
        self.assertEqual(3, results["n_picks_similar"])
        with open(results["filepath_picks"]) as f:
            saved = _yaml.full_load(f)
        self.assertEqual("Circle", saved["Shape"])
        self.assertEqual(1.5, saved["Diameter"])
        self.assertEqual(3, len(saved["Centers"]))

    @patch(
        "picasso_workflow.picasso_set.analyse_picks."
        "postprocess.remove_locs_in_picks"
    )
    @patch("picasso_workflow.picasso_set.analyse_picks.io.load_picks")
    def test_picasso_remove_locs_in_picks(self, mock_lp, mock_rm):
        mock_lp.return_value = self._PICKS
        mock_rm.return_value = self.ap.locs.iloc[:4]
        with patch.object(self.ap, "_save_locs"):
            parameters, results = self.ap.picasso_remove_locs_in_picks(
                0, {"picks_file": "picks.yaml"}
            )
        self.assertEqual(4, results["nlocs"])
        self.assertIn("Remove picks", self.ap.info[-1]["Generated by"])

    @patch("picasso_workflow.picasso_set.analyse_picks.io.save_datasets")
    @patch(
        "picasso_workflow.picasso_set.analyse_picks."
        "postprocess.pick_properties"
    )
    @patch(
        "picasso_workflow.picasso_set.analyse_picks." "postprocess.picked_locs"
    )
    @patch("picasso_workflow.picasso_set.analyse_picks.io.load_picks")
    def test_picasso_pick_properties(
        self, mock_lp, mock_pl, mock_props, mock_sd
    ):
        mock_lp.return_value = self._PICKS
        mock_pl.return_value = [self.ap.locs.iloc[:5]]
        mock_props.return_value = pd.DataFrame({"n_events": [3, 5]})
        parameters, results = self.ap.picasso_pick_properties(
            0, {"picks_file": "picks.yaml"}
        )
        # library defaults
        self.assertEqual(3, mock_props.call_args[1]["max_dark_time"])
        self.assertEqual(0.03, mock_props.call_args[1]["influx_rate"])
        mock_sd.assert_called_once()
        self.assertEqual(2, results["n_picks"])
        self.assertIn("filepath_pick_properties", results)

    @patch(
        "picasso_workflow.picasso_set.analyse_picks."
        "postprocess.pick_kinetics"
    )
    @patch(
        "picasso_workflow.picasso_set.analyse_picks." "postprocess.picked_locs"
    )
    @patch("picasso_workflow.picasso_set.analyse_picks.io.load_picks")
    def test_picasso_pick_kinetics(self, mock_lp, mock_pl, mock_pk):
        mock_lp.return_value = self._PICKS
        mock_pl.return_value = [self.ap.locs.iloc[:5]]
        out_locs = self.ap.locs.iloc[:5]
        mock_pk.return_value = (
            np.array([5.0, 7.0]),
            np.array([10.0, 20.0]),
            np.array([3, 4]),
            out_locs,
            np.array([0]),
        )
        with patch.object(self.ap, "_save_locs"):
            parameters, results = self.ap.picasso_pick_kinetics(
                0, {"picks_file": "picks.yaml"}
            )
        self.assertEqual(3, mock_pk.call_args[1]["max_dark_time"])
        self.assertEqual(6.0, results["mean_length_frames"])
        self.assertEqual(15.0, results["mean_dark_frames"])
        self.assertEqual(1, results["n_picks_kept"])
        self.assertIs(self.ap.locs, out_locs)

    @patch("picasso_workflow.picasso_set.analyse_picks.io.save_locs")
    @patch(
        "picasso_workflow.picasso_set.analyse_picks."
        "postprocess.calculate_fret"
    )
    @patch("picasso_workflow.picasso_set.analyse_picks.io.load_locs")
    def test_picasso_fret(self, mock_ll, mock_fret, mock_sl):
        mock_ll.return_value = (self.ap.locs, [{"Frames": 10}])
        mock_fret.return_value = (
            {
                "fret_events": np.array([0.5, 0.7]),
                "fret_timepoints": np.array([1, 2]),
            },
            self.ap.locs.iloc[:2],
        )
        parameters, results = self.ap.picasso_fret(
            0,
            {"acc_locs_file": "acc.hdf5", "don_locs_file": "don.hdf5"},
        )
        self.assertEqual(2, results["n_fret_events"])
        self.assertAlmostEqual(0.6, results["mean_fret"])
        mock_sl.assert_called_once()
        self.assertTrue(os.path.isfile(results["filepath_fret_events"]))

    @patch(
        "picasso_workflow.picasso_set.analyse_picks."
        "postprocess.calculate_fret"
    )
    @patch("picasso_workflow.picasso_set.analyse_picks.io.load_locs")
    def test_picasso_fret_no_events(self, mock_ll, mock_fret):
        mock_ll.return_value = (self.ap.locs, [{"Frames": 10}])
        mock_fret.return_value = ({"fret_events": []}, [])
        parameters, results = self.ap.picasso_fret(
            0,
            {"acc_locs_file": "acc.hdf5", "don_locs_file": "don.hdf5"},
        )
        self.assertFalse(results["success"])

    @patch("picasso_workflow.picasso_set.analyse_picks.io.save_locs")
    @patch("picasso.masking.mask_locs")
    @patch("picasso.masking.mask_image")
    @patch("picasso.masking.generate_image")
    def test_picasso_mask_locs(self, mock_gi, mock_mi, mock_ml, mock_sl):
        mock_gi.return_value = np.random.rand(8, 8)
        mock_mi.return_value = (np.ones((8, 8), dtype=bool), 0.5)
        mock_ml.return_value = (self.ap.locs.iloc[:6], self.ap.locs.iloc[6:])
        with patch.object(self.ap, "_save_locs"):
            parameters, results = self.ap.picasso_mask_locs(
                0, {"disp_px_size": 100.0, "blur": 2.0}
            )
        # library default thresholding method
        self.assertEqual("otsu", mock_mi.call_args[0][1])
        self.assertEqual(6, results["nlocs_in"])
        self.assertEqual(4, results["nlocs_out"])
        self.assertEqual(0.5, results["threshold"])
        self.assertEqual(6, len(self.ap.locs))
        self.assertTrue(os.path.isfile(results["filepath_mask"]))
        self.assertTrue(os.path.isfile(results["fp_fig_mask"]))

    @patch("picasso_workflow.picasso_set.analyse_picks.postprocess.nena")
    def test_picasso_nena(self, mock_nena):
        self.ap.info.append({"Pixelsize": 130})
        mock_nena.return_value = ({"best_vals": None}, 0.4)
        parameters, results = self.ap.picasso_nena(0, {})
        self.assertAlmostEqual(0.4, results["nena_px"])
        self.assertAlmostEqual(52.0, results["nena_nm"])

    @patch("picasso_workflow.picasso_set.analyse_picks.postprocess.frc")
    def test_picasso_frc(self, mock_frc):
        freqs = np.linspace(0.001, 0.05, 50)
        mock_frc.return_value = {
            "frequencies": freqs,
            "frc_curve": np.random.rand(50),
            "frc_curve_smooth": np.random.rand(50),
            "resolution": 25.0,
            "images": None,
        }
        parameters, results = self.ap.picasso_frc(0, {})
        # full-FOV viewport from the metadata
        self.assertEqual(((0, 0), (32, 64)), mock_frc.call_args[0][2])
        self.assertEqual(42, mock_frc.call_args[1]["random_seed"])
        self.assertEqual(25.0, results["resolution_nm"])
        self.assertTrue(os.path.isfile(results["fp_fig_frc"]))
        self.assertTrue(os.path.isfile(results["filepath_frc"]))

    @patch(
        "picasso_workflow.picasso_set.analyse_core."
        "postprocess.compute_local_density"
    )
    def test_picasso_density(self, mock_cld):
        mock_cld.return_value = self.ap.locs
        with patch.object(self.ap, "_save_locs") as mock_save:
            parameters, results = self.ap.picasso_density(0, {"radius": 1.5})

        mock_cld.assert_called_once()
        self.assertEqual(1.5, mock_cld.call_args[0][2])
        self.assertTrue(results["success"])
        self.assertEqual(len(self.ap.locs), results["nlocs"])
        # saved like the CLI's _density.hdf5 output
        self.assertEqual(
            os.path.join(results["folder"], "locs_density.hdf5"),
            results["filepath_locs_density"],
        )
        mock_save.assert_any_call(results["filepath_locs_density"])
        # info entry mirrors the CLI
        self.assertIn("Density", self.ap.info[-1]["Generated by"])
        self.assertEqual(1.5, self.ap.info[-1]["Radius"])
        self.assertTrue(os.path.isdir(results["folder"]))


class TestPicassoSetGenericReporter(unittest.TestCase):
    """The generic reporter fallback serves every picasso-set module."""

    @patch("picasso_workflow.confluence.ConfluenceInterface")
    def setUp(self, mock_cfi):
        mock_instance = MagicMock()
        mock_instance.create_page.return_value = 534
        mock_instance.update_page_content.return_value = None
        mock_cfi.return_value = mock_instance
        self.cr = confluence.ConfluenceReporter(
            "url", "space", "parentpage", "my test report"
        )
        self.result_folder = tempfile.mkdtemp()

    def tearDown(self):
        shutil.rmtree(self.result_folder, ignore_errors=True)

    def _typical_results(self):
        fp_fig = os.path.join(self.result_folder, "plot.png")
        open(fp_fig, "w").close()
        fp_locs = os.path.join(self.result_folder, "locs_density.hdf5")
        open(fp_locs, "w").close()
        return {
            "folder": self.result_folder,
            "start time": "now",
            "end time": "later",
            "duration": 65.5,
            "nlocs": 1234,
            "filepath_locs_density": fp_locs,
        }

    def test_all_picasso_set_modules_resolve(self):
        for name in sorted(_picasso_set_names()):
            self.assertTrue(callable(getattr(self.cr, name)))

    def test_unknown_names_still_raise(self):
        with self.assertRaises(AttributeError):
            self.cr.not_a_module
        with self.assertRaises(AttributeError):
            self.cr._picasso_private_probe

    def test_generic_report_content(self):
        results = self._typical_results()
        text = self.cr.picasso_density(
            3, {"radius": 1.5}, results, postpone_report=True
        )
        self.assertIn("Module 03: picasso_density", text)
        self.assertIn("compute_local_density", text)
        self.assertIn("radius", text)
        # image embedded, non-image output listed
        self.assertIn("plot.png", text)
        self.assertIn("locs_density.hdf5", text)

    def test_generic_report_posts(self):
        results = self._typical_results()
        retval = self.cr.picasso_density(3, {"radius": 1.5}, results)
        self.assertIsNone(retval)
        self.cr.ci.upload_attachment.assert_called()
        self.cr.ci.update_page_content.assert_called()

    def test_generic_report_without_folder(self):
        # must not fail when the folder is gone (e.g. moved results)
        text = self.cr.picasso_density(
            1,
            {"radius": 1.5},
            {"folder": "/nonexistent", "duration": 1.0},
            postpone_report=True,
        )
        self.assertIn("Module 01: picasso_density", text)

    def test_generic_report_stale_figure_paths_still_embedded(self):
        """Stale absolute figure paths are handed to upload_attachment
        (which re-resolves by basename on the HTML side) instead of being
        silently dropped by an isfile pre-check."""
        text = self.cr.picasso_density(
            2,
            {"radius": 1.5},
            {
                "folder": "/moved/away",
                "duration": 1.0,
                "fp_fig": "/moved/away/plot.png",
            },
            postpone_report=True,
        )
        self.cr.ci.upload_attachment.assert_called_once_with(
            self.cr.report_page_id, "/moved/away/plot.png"
        )
        self.assertIn("plot.png", text)


class TestPicassoSetHtmlReporter(unittest.TestCase):
    """HTMLReporter inherits the generic picasso-set reporting."""

    def setUp(self):
        self.report_dir = tempfile.mkdtemp()
        self.hr = html_reporter.HTMLReporter(
            self.report_dir, "picasso set report"
        )

    def tearDown(self):
        shutil.rmtree(self.report_dir, ignore_errors=True)

    def test_generic_report_renders(self):
        result_folder = os.path.join(self.report_dir, "00_picasso_density")
        os.makedirs(result_folder)
        fp_fig = os.path.join(result_folder, "plot.png")
        open(fp_fig, "w").close()
        results = {
            "folder": result_folder,
            "duration": 3.0,
            "nlocs": 12,
        }
        self.hr.picasso_density(0, {"radius": 1.5}, results)
        report_file = self.hr.ci.html_path
        with open(report_file, encoding="utf-8") as f:
            content = f.read()
        self.assertIn("picasso_density", content)
        self.assertIn("plot.png", content)


if __name__ == "__main__":
    unittest.main()
