#!/usr/bin/env python
"""
Module Name: test_picasso_set.py
Author: Heinrich Grabmayr
Initial Date: October 5, 2026
Description: Test the picasso-set module layer: reconcile the registry
    entries against the mixin implementations, unit-test the analysis
    modules (picasso mocked), and exercise the generic reporter fallback.
"""

import logging
import os
import shutil
import tempfile
import unittest
from unittest.mock import MagicMock, patch

import numpy as np
import pandas as pd

from picasso_workflow import analyse, confluence, html_reporter
from picasso_workflow.modulespec import MODULE_REGISTRY
from picasso_workflow.picasso_set.params import (
    PICASSO_SET_PARAMS,
    PICASSO_SET_SUMMARIES,
    docstring,
)

logger = logging.getLogger(__name__)


def _picasso_set_names():
    """The registered picasso-set module names."""
    return {
        name
        for name, spec in MODULE_REGISTRY.items()
        if spec.module_set == "picasso"
    }


class TestPicassoSetReconciliation(unittest.TestCase):
    """Registry entries and mixin implementations must match 1:1."""

    def test_every_spec_is_implemented(self):
        for name in sorted(_picasso_set_names()):
            self.assertTrue(
                callable(getattr(analyse.AutoPicasso, name, None)),
                f"picasso-set spec {name} has no AutoPicasso implementation",
            )

    def test_every_implementation_has_a_spec(self):
        implemented = {
            name
            for name in dir(analyse.AutoPicasso)
            if name.startswith("picasso_")
            and callable(getattr(analyse.AutoPicasso, name))
        }
        orphan = implemented - _picasso_set_names()
        self.assertEqual(
            set(),
            orphan,
            f"picasso_* methods without a ModuleSpec: {sorted(orphan)}",
        )

    def test_params_and_summaries_complete(self):
        for name in sorted(_picasso_set_names()):
            self.assertIn(name, PICASSO_SET_PARAMS)
            self.assertIn(name, PICASSO_SET_SUMMARIES)
            self.assertTrue(docstring(name))

    def test_all_modules_have_unit_tests(self):
        """Every picasso-set module needs a test in TestPicassoSetModules."""
        missing = [
            name
            for name in sorted(_picasso_set_names())
            if not callable(
                getattr(TestPicassoSetModules, f"test_{name}", None)
            )
        ]
        if missing:
            raise NotImplementedError(
                f"Unit tests of picasso-set modules {missing} not implemented!"
            )


class TestPicassoSetModules(unittest.TestCase):
    """Unit tests of the picasso-set analysis modules (picasso mocked)."""

    def setUp(self):
        self.results_folder = tempfile.mkdtemp()
        analysis_config = {
            "camera_info": {
                "Gain": 1,
                "Sensitivity": 0.45,
                "Baseline": 100,
                "Qe": 0.82,
                "Pixelsize": 130,  # nm
            },
            "gpufit_installed": False,
        }
        self.ap = analyse.AutoPicasso(self.results_folder, analysis_config)
        locs_dtype = [
            ("frame", "u4"),
            ("x", "f4"),
            ("y", "f4"),
            ("photons", "f4"),
            ("lpx", "f4"),
            ("lpy", "f4"),
        ]
        self.ap.locs = pd.DataFrame(
            np.rec.array(
                [
                    tuple([i] + list(np.random.rand(len(locs_dtype) - 1)))
                    for i in range(10)
                ],
                dtype=locs_dtype,
            )
        )
        self.ap.info = [{"Width": 64, "Height": 32, "Frames": 1000}]

    def tearDown(self):
        shutil.rmtree(self.results_folder, ignore_errors=True)

    def _drift(self, n=5):
        return pd.DataFrame({"x": np.zeros(n), "y": np.zeros(n)})

    @patch("picasso_workflow.picasso_set.analyse_core.localize.localize")
    def test_picasso_localize(self, mock_localize):
        self.ap.movie = np.random.randint(
            0, 1000, size=(5, 32, 64), dtype=np.uint16
        )
        fit_info = {"Generated by": "Picasso Localize"}
        mock_localize.return_value = (
            self.ap.locs,
            self.ap.info + [fit_info],
        )
        with patch.object(self.ap, "_save_locs"):
            parameters, results = self.ap.picasso_localize(0, {})

        kwargs = mock_localize.call_args[1]
        # CLI defaults through the fit-method map
        self.assertEqual("gaussmle", kwargs["fitting_method"])
        self.assertEqual(
            5000,
            kwargs["identification_parameters"]["Min. Net Gradient"],
        )
        self.assertEqual(7, kwargs["identification_parameters"]["Box Size"])
        # convergence/max_iterations 0 -> the method's own defaults
        self.assertIsNone(kwargs["eps"])
        self.assertIsNone(kwargs["max_it"])
        # camera params default to the loaded camera config, not the
        # CLI literals (documented deviation)
        self.assertEqual(
            {
                "Baseline": 100,
                "Sensitivity": 0.45,
                "Gain": 1,
                "Qe": 0.82,
                "Pixelsize": 130,
            },
            kwargs["camera_info"],
        )
        self.assertEqual("Picasso Localize", self.ap.info[-1]["Generated by"])
        self.assertIn("filepath_locs", results)
        self.assertEqual(len(self.ap.locs), results["nlocs"])

    @patch("picasso_workflow.picasso_set.analyse_core.localize.localize")
    def test_picasso_localize_explicit_camera_params(self, mock_localize):
        self.ap.movie = np.zeros((2, 8, 8), dtype=np.uint16)
        mock_localize.return_value = (self.ap.locs, self.ap.info + [{}])
        with patch.object(self.ap, "_save_locs"):
            self.ap.picasso_localize(0, {"baseline": 200, "pixelsize": 108})
        cam = mock_localize.call_args[1]["camera_info"]
        self.assertEqual(200, cam["Baseline"])
        self.assertEqual(108, cam["Pixelsize"])
        # unset ones still come from the config
        self.assertEqual(0.45, cam["Sensitivity"])

    def test_picasso_localize_gpu_guard(self):
        with patch(
            "picasso_workflow.picasso_set.analyse_core."
            "localize.CUDA_AVAILABLE",
            False,
        ):
            with self.assertRaises(RuntimeError):
                self.ap.picasso_localize(0, {"fit_method": "mle-gpu"})

    def test_picasso_localize_spline_requires_calibration(self):
        with self.assertRaises(ValueError):
            self.ap.picasso_localize(0, {"fit_method": "spline"})

    def test_picasso_localize_3d_requires_zc_and_mf(self):
        with self.assertRaises(ValueError):
            self.ap.picasso_localize(0, {"fit_method": "lq-3d"})
        with self.assertRaises(ValueError):
            self.ap.picasso_localize(
                0, {"fit_method": "lq-3d", "zc": "cal.yaml"}
            )

    @patch("picasso_workflow.picasso_set.analyse_core.postprocess.plot_drift")
    @patch("picasso_workflow.picasso_set.analyse_core.io.save_drift")
    @patch("picasso_workflow.picasso_set.analyse_core.postprocess.undrift")
    def test_picasso_undrift_rcc(self, mock_undrift, mock_sd, mock_pd):
        drift = self._drift()
        mock_undrift.return_value = (drift, self.ap.locs)
        with patch.object(self.ap, "_save_locs"):
            parameters, results = self.ap.picasso_undrift_rcc(
                0, {"segmentation": 500}
            )
        self.assertEqual(500, mock_undrift.call_args[0][2])
        self.assertIs(self.ap.drift, drift)
        mock_sd.assert_called_once()
        self.assertIn("filepath_driftfile", results)
        self.assertIn("filepath_locs_undrift", results)
        entry = self.ap.info[-1]
        self.assertIn("Undrift", entry["Generated by"])
        self.assertEqual(500, entry["Segmentation"])

    @patch("picasso_workflow.picasso_set.analyse_core.postprocess.plot_drift")
    @patch("picasso_workflow.picasso_set.analyse_core.io.save_drift")
    @patch("picasso_workflow.picasso_set.analyse_core.aim.aim")
    def test_picasso_undrift_aim(self, mock_aim, mock_sd, mock_pd):
        drift = self._drift()
        new_info = self.ap.info + [{"Generated by": "Picasso AIM"}]
        mock_aim.return_value = (self.ap.locs, new_info, drift)
        with patch.object(self.ap, "_save_locs"):
            parameters, results = self.ap.picasso_undrift_aim(0, {})
        # CLI defaults
        args = mock_aim.call_args[0]
        self.assertEqual(100, args[2])
        self.assertAlmostEqual(20 / 130, args[3])
        self.assertAlmostEqual(60 / 130, args[4])
        self.assertIs(self.ap.drift, drift)
        self.assertIn("filepath_locs_aim", results)

    @patch("picasso_workflow.picasso_set.analyse_core.postprocess.plot_drift")
    @patch("picasso_workflow.picasso_set.analyse_core.io.save_drift")
    @patch(
        "picasso_workflow.picasso_set.analyse_core."
        "postprocess.undrift_from_fiducials"
    )
    @patch("picasso_workflow.picasso_set.analyse_core.postprocess.undrift")
    def test_picasso_undrift_fiducials(
        self, mock_undrift, mock_uff, mock_sd, mock_pd
    ):
        drift = self._drift()
        mock_undrift.return_value = (drift, self.ap.locs)
        new_info = self.ap.info + [
            {"Number of picks": 7, "Pick radius (nm)": 500.0}
        ]
        mock_uff.return_value = (self.ap.locs, new_info, drift)
        with patch.object(self.ap, "_save_locs"):
            parameters, results = self.ap.picasso_undrift_fiducials(0, {})
        # CLI composite: pre-RCC with segmentation 2000
        self.assertEqual(2000, mock_undrift.call_args[0][2])
        entry = self.ap.info[-1]
        self.assertEqual(7, entry["Number of picks"])
        self.assertEqual(2000, entry["pre-RCC segmentation"])
        self.assertIn("filepath_locs_undrift_fiducials", results)

    @patch("picasso_workflow.picasso_set.analyse_core.postprocess.link")
    def test_picasso_link(self, mock_link):
        mock_link.return_value = self.ap.locs
        with patch.object(self.ap, "_save_locs"):
            parameters, results = self.ap.picasso_link(0, {})
        # CLI defaults
        self.assertEqual(1.0, mock_link.call_args[0][2])
        self.assertEqual(1, mock_link.call_args[0][3])
        entry = self.ap.info[-1]
        self.assertEqual(1.0, entry["Maximum Distance"])
        self.assertEqual(1, entry["Maximum Transient Dark Time"])
        self.assertIn("filepath_locs_link", results)

    @patch(
        "picasso_workflow.picasso_set.analyse_core."
        "postprocess.compute_dark_times"
    )
    def test_picasso_dark(self, mock_dark):
        mock_dark.return_value = self.ap.locs
        with patch.object(self.ap, "_save_locs"):
            parameters, results = self.ap.picasso_dark(0, {})
        mock_dark.assert_called_once()
        self.assertIn("Dark", self.ap.info[-1]["Generated by"])
        self.assertIn("filepath_locs_dark", results)

    @patch("picasso_workflow.picasso_set.analyse_core.io.save_datasets")
    @patch("picasso_workflow.picasso_set.analyse_core.postprocess.groupprops")
    def test_picasso_groupprops(self, mock_gp, mock_sd):
        groups = pd.DataFrame({"group": [0, 1], "n_events": [3, 5]})
        mock_gp.return_value = groups
        parameters, results = self.ap.picasso_groupprops(0, {})
        mock_sd.assert_called_once()
        self.assertEqual(2, results["n_groups"])
        self.assertIn("filepath_locs_groupprops", results)

    @patch(
        "picasso_workflow.picasso_set.analyse_core."
        "postprocess.pair_correlation"
    )
    def test_picasso_pair_correlation(self, mock_pc):
        bins = np.linspace(0.1, 10, 100)
        mock_pc.return_value = (bins, np.random.rand(100))
        parameters, results = self.ap.picasso_pair_correlation(0, {})
        # CLI defaults
        self.assertEqual(0.1, mock_pc.call_args[0][2])
        self.assertEqual(10, mock_pc.call_args[0][3])
        self.assertTrue(os.path.isfile(results["fp_fig_pair_correlation"]))
        self.assertTrue(os.path.isfile(results["filepath_pair_correlation"]))

    @patch("picasso_workflow.picasso_set.analyse_core.io.save_locs")
    @patch(
        "picasso_workflow.picasso_set.analyse_core."
        "clusterer.find_cluster_centers"
    )
    @patch("picasso_workflow.picasso_set.analyse_core.clusterer.dbscan")
    def test_picasso_dbscan(self, mock_dbscan, mock_fcc, mock_sl):
        mock_dbscan.return_value = (self.ap.locs, {"Generated by": "DBSCAN"})
        mock_fcc.return_value = self.ap.locs.iloc[:3]
        with patch.object(self.ap, "_save_locs"):
            parameters, results = self.ap.picasso_dbscan(
                0, {"radius": 0.5, "density": 4}
            )
        args = mock_dbscan.call_args
        self.assertEqual(0.5, args[0][1])
        self.assertEqual(4, args[0][2])
        self.assertEqual(3, results["nclusters"])
        self.assertIn("filepath_locs_dbclusters", results)

    @patch("picasso_workflow.picasso_set.analyse_core.io.save_locs")
    @patch(
        "picasso_workflow.picasso_set.analyse_core."
        "clusterer.find_cluster_centers"
    )
    @patch("picasso_workflow.picasso_set.analyse_core.clusterer.hdbscan")
    def test_picasso_hdbscan(self, mock_hdbscan, mock_fcc, mock_sl):
        mock_hdbscan.return_value = (
            self.ap.locs,
            {"Generated by": "HDBSCAN"},
        )
        mock_fcc.return_value = self.ap.locs.iloc[:2]
        with patch.object(self.ap, "_save_locs"):
            parameters, results = self.ap.picasso_hdbscan(
                0, {"min_cluster": 10, "min_samples": 5}
            )
        args = mock_hdbscan.call_args[0]
        self.assertEqual(10, args[1])
        self.assertEqual(5, args[2])
        self.assertEqual(2, results["nclusters"])
        self.assertIn("filepath_locs_hdbclusters", results)

    @patch("picasso_workflow.picasso_set.analyse_core.io.save_locs")
    @patch(
        "picasso_workflow.picasso_set.analyse_core."
        "clusterer.find_cluster_centers"
    )
    @patch("picasso_workflow.picasso_set.analyse_core.clusterer.cluster")
    def test_picasso_smlm_cluster(self, mock_cluster, mock_fcc, mock_sl):
        mock_cluster.return_value = (self.ap.locs, {"Generated by": "SMLM"})
        mock_fcc.return_value = self.ap.locs.iloc[:4]
        with patch.object(self.ap, "_save_locs"):
            parameters, results = self.ap.picasso_smlm_cluster(
                0, {"radius": 0.3, "min_locs": 8}
            )
        kwargs = mock_cluster.call_args[1]
        self.assertEqual(0.3, kwargs["radius_xy"])
        self.assertEqual(8, kwargs["min_locs"])
        self.assertFalse(kwargs["frame_analysis"])  # CLI default basic_fa
        self.assertEqual(4, results["nclusters"])
        self.assertIn("filepath_locs_cluster_centers", results)

    @patch("picasso_workflow.picasso_set.analyse_core.pd.read_hdf")
    def test_picasso_nneighbor(self, mock_read_hdf):
        mock_read_hdf.return_value = pd.DataFrame(
            {
                "com_x": [0.0, 1.0, 5.0],
                "com_y": [0.0, 0.0, 0.0],
            }
        )
        parameters, results = self.ap.picasso_nneighbor(
            0, {"files": "clusters.hdf5"}
        )
        self.assertEqual(3, results["n_points"])
        self.assertTrue(os.path.isfile(results["filepath_minval"]))
        minvals = np.loadtxt(results["filepath_minval"])
        np.testing.assert_allclose(minvals, [1.0, 1.0, 4.0])

    @patch("picasso_workflow.picasso_set.analyse_core.io.save_locs")
    @patch("picasso_workflow.picasso_set.analyse_core.io.load_clusters")
    def test_picasso_clusterfilter(self, mock_lc, mock_sl):
        self.ap.locs["group"] = [0, 0, 1, 1, 2, 2, 3, 3, 4, 4]
        mock_lc.return_value = pd.DataFrame(
            {
                "groups": [0, 1, 2, 3, 4],
                "n_events": [1.0, 5.0, 5.0, 5.0, 9.0],
            }
        )
        parameters, results = self.ap.picasso_clusterfilter(
            0,
            {
                "clusterfile": "clusters.hdf5",
                "parameter": "n_events",
                "minval": 2.0,
                "maxval": 8.0,
            },
        )
        self.assertEqual(6, results["nlocs_in"])
        self.assertEqual(4, results["nlocs_out"])
        # workflow continues with the in-range locs
        self.assertEqual(6, len(self.ap.locs))
        self.assertIn("Clusterfilter - in", self.ap.info[-1]["Generated by"])

    @patch("picasso_workflow.picasso_set.analyse_core.io.load_clusters")
    def test_picasso_clusterfilter_aborts_on_empty_range(self, mock_lc):
        self.ap.locs["group"] = np.zeros(len(self.ap.locs), dtype=int)
        mock_lc.return_value = pd.DataFrame({"groups": [0], "n_events": [1.0]})
        parameters, results = self.ap.picasso_clusterfilter(
            0,
            {
                "clusterfile": "clusters.hdf5",
                "parameter": "n_events",
                "minval": 2.0,
                "maxval": 8.0,
            },
        )
        self.assertFalse(results["success"])

    @patch(
        "picasso_workflow.picasso_set.analyse_core."
        "postprocess.cluster_combine"
    )
    def test_picasso_cluster_combine(self, mock_cc):
        mock_cc.return_value = self.ap.locs
        with patch.object(self.ap, "_save_locs"):
            parameters, results = self.ap.picasso_cluster_combine(0, {})
        mock_cc.assert_called_once()
        self.assertIn("Combine", self.ap.info[-1]["Generated by"])
        self.assertIn("filepath_locs_comb", results)

    @patch(
        "picasso_workflow.picasso_set.analyse_core."
        "postprocess.cluster_combine_dist"
    )
    def test_picasso_cluster_combine_dist(self, mock_ccd):
        self.ap.info.append({"Pixelsize": 130})
        mock_ccd.return_value = self.ap.locs
        with patch.object(self.ap, "_save_locs"):
            parameters, results = self.ap.picasso_cluster_combine_dist(0, {})
        # pixelsize read from metadata like the CLI
        self.assertEqual(130, mock_ccd.call_args[0][1])
        self.assertIn("CombineDist", self.ap.info[-1]["Generated by"])

    @patch("picasso_workflow.picasso_set.analyse_core.g5m.g5m")
    def test_picasso_g5m(self, mock_g5m):
        mols = self.ap.locs.iloc[:3]
        g5m_info = self.ap.info + [{"Generated by": "Picasso G5M"}]
        mock_g5m.return_value = (mols, None, g5m_info)
        with patch.object(self.ap, "_save_locs"):
            parameters, results = self.ap.picasso_g5m(0, {})
        kwargs = mock_g5m.call_args[1]
        # CLI defaults
        self.assertEqual(10, kwargs["min_locs"])
        self.assertEqual("local", kwargs["loc_prec_handle"])
        self.assertEqual((0.8, 1.5), kwargs["sigma_bounds"])
        self.assertEqual(3, kwargs["max_rounds_without_best_bic"])
        self.assertTrue(kwargs["postprocess"])
        self.assertEqual("group", kwargs["group_column"])
        self.assertIsNone(kwargs["calibration"])
        self.assertEqual(3, results["n_molecules"])
        self.assertIs(self.ap.locs, mols)
        self.assertIn("filepath_locs_molmap", results)

    def test_picasso_g5m_3d_astigmatism_requires_calibration(self):
        self.ap.locs["z"] = np.zeros(len(self.ap.locs))
        with self.assertRaises(ValueError):
            self.ap.picasso_g5m(0, {})

    @patch("picasso_workflow.picasso_set.analyse_core.render.render")
    def test_picasso_render(self, mock_render):
        mock_render.return_value = (len(self.ap.locs), np.random.rand(32, 64))
        parameters, results = self.ap.picasso_render(0, {})
        kwargs = mock_render.call_args[1]
        # CLI defaults
        self.assertEqual(10.0, kwargs["disp_px_size"])
        self.assertEqual("convolve", kwargs["blur_method"])
        self.assertTrue(os.path.isfile(results["fp_fig_render"]))
        self.assertEqual(len(self.ap.locs), results["n_rendered"])

    @patch("picasso_workflow.picasso_set.analyse_core.render.render")
    def test_picasso_render_blur_none(self, mock_render):
        mock_render.return_value = (0, np.random.rand(8, 8))
        self.ap.picasso_render(0, {"blur_method": "none"})
        self.assertIsNone(mock_render.call_args[1]["blur_method"])

    @patch("picasso_workflow.picasso_set.analyse_core.io.save_locs")
    @patch("picasso_workflow.picasso_set.analyse_core.postprocess.align")
    @patch("picasso_workflow.picasso_set.analyse_core.io.load_locs")
    def test_picasso_align(self, mock_ll, mock_align, mock_sl):
        mock_ll.return_value = (self.ap.locs, [{"Frames": 1000}])
        mock_align.return_value = [self.ap.locs, self.ap.locs]
        parameters, results = self.ap.picasso_align(
            0, {"files": ["a.hdf5", "b.hdf5"]}
        )
        self.assertEqual(2, len(results["filepaths_aligned"]))
        self.assertTrue(
            results["filepaths_aligned"][0].endswith("a_align.hdf5")
        )
        self.assertEqual(2, mock_sl.call_count)

    @patch("picasso_workflow.picasso_set.analyse_core.lib.merge_locs")
    @patch("picasso_workflow.picasso_set.analyse_core.io.load_locs")
    def test_picasso_join(self, mock_ll, mock_merge):
        mock_ll.return_value = (self.ap.locs, [{"Frames": 10}])
        mock_merge.return_value = self.ap.locs
        with patch.object(self.ap, "_save_locs"):
            parameters, results = self.ap.picasso_join(
                0, {"files": ["a.hdf5", "b.hdf5"]}
            )
        # frames reindexed by default (CLI keepindex defaults to off)
        self.assertTrue(mock_merge.call_args[1]["increment_frames"])
        self.assertEqual(
            int(self.ap.locs["frame"].max()) + 1, self.ap.info[0]["Frames"]
        )
        self.assertIn("Join", self.ap.info[-1]["Generated by"])
        self.assertIn("filepath_locs_join", results)

    # --- tier 2: picks/postprocessing ---------------------------------

    _PICKS = ([[1.0, 2.0], [3.0, 4.0]], "Circle", 1.5)

    @patch(
        "picasso_workflow.picasso_set.analyse_picks." "postprocess.picked_locs"
    )
    @patch("picasso_workflow.picasso_set.analyse_picks.io.load_picks")
    def test_picasso_picked_locs(self, mock_lp, mock_pl):
        mock_lp.return_value = self._PICKS
        mock_pl.return_value = [self.ap.locs.iloc[:3], self.ap.locs.iloc[3:6]]
        with patch.object(self.ap, "_save_locs"):
            parameters, results = self.ap.picasso_picked_locs(
                0, {"picks_file": "picks.yaml"}
            )
        self.assertEqual(2, results["n_picks"])
        self.assertEqual(6, results["nlocs"])
        self.assertEqual(6, len(self.ap.locs))
        self.assertIn("Pick", self.ap.info[-1]["Generated by"])
        self.assertTrue(mock_pl.call_args[1]["add_group"])

    @patch(
        "picasso_workflow.picasso_set.analyse_picks."
        "postprocess.pick_similar"
    )
    @patch("picasso_workflow.picasso_set.analyse_picks.io.load_picks")
    def test_picasso_pick_similar(self, mock_lp, mock_ps):
        import yaml as _yaml

        mock_lp.return_value = self._PICKS
        mock_ps.return_value = [[1.0, 2.0], [3.0, 4.0], [5.0, 6.0]]
        parameters, results = self.ap.picasso_pick_similar(
            0, {"picks_file": "picks.yaml"}
        )
        self.assertEqual(2.0, mock_ps.call_args[1]["std_range"])
        self.assertEqual(2, results["n_picks_input"])
        self.assertEqual(3, results["n_picks_similar"])
        with open(results["filepath_picks"]) as f:
            saved = _yaml.full_load(f)
        self.assertEqual("Circle", saved["Shape"])
        self.assertEqual(1.5, saved["Diameter"])
        self.assertEqual(3, len(saved["Centers"]))

    @patch(
        "picasso_workflow.picasso_set.analyse_picks."
        "postprocess.remove_locs_in_picks"
    )
    @patch("picasso_workflow.picasso_set.analyse_picks.io.load_picks")
    def test_picasso_remove_locs_in_picks(self, mock_lp, mock_rm):
        mock_lp.return_value = self._PICKS
        mock_rm.return_value = self.ap.locs.iloc[:4]
        with patch.object(self.ap, "_save_locs"):
            parameters, results = self.ap.picasso_remove_locs_in_picks(
                0, {"picks_file": "picks.yaml"}
            )
        self.assertEqual(4, results["nlocs"])
        self.assertIn("Remove picks", self.ap.info[-1]["Generated by"])

    @patch("picasso_workflow.picasso_set.analyse_picks.io.save_datasets")
    @patch(
        "picasso_workflow.picasso_set.analyse_picks."
        "postprocess.pick_properties"
    )
    @patch(
        "picasso_workflow.picasso_set.analyse_picks." "postprocess.picked_locs"
    )
    @patch("picasso_workflow.picasso_set.analyse_picks.io.load_picks")
    def test_picasso_pick_properties(
        self, mock_lp, mock_pl, mock_props, mock_sd
    ):
        mock_lp.return_value = self._PICKS
        mock_pl.return_value = [self.ap.locs.iloc[:5]]
        mock_props.return_value = pd.DataFrame({"n_events": [3, 5]})
        parameters, results = self.ap.picasso_pick_properties(
            0, {"picks_file": "picks.yaml"}
        )
        # library defaults
        self.assertEqual(3, mock_props.call_args[1]["max_dark_time"])
        self.assertEqual(0.03, mock_props.call_args[1]["influx_rate"])
        mock_sd.assert_called_once()
        self.assertEqual(2, results["n_picks"])
        self.assertIn("filepath_pick_properties", results)

    @patch(
        "picasso_workflow.picasso_set.analyse_picks."
        "postprocess.pick_kinetics"
    )
    @patch(
        "picasso_workflow.picasso_set.analyse_picks." "postprocess.picked_locs"
    )
    @patch("picasso_workflow.picasso_set.analyse_picks.io.load_picks")
    def test_picasso_pick_kinetics(self, mock_lp, mock_pl, mock_pk):
        mock_lp.return_value = self._PICKS
        mock_pl.return_value = [self.ap.locs.iloc[:5]]
        out_locs = self.ap.locs.iloc[:5]
        mock_pk.return_value = (
            np.array([5.0, 7.0]),
            np.array([10.0, 20.0]),
            np.array([3, 4]),
            out_locs,
            np.array([0]),
        )
        with patch.object(self.ap, "_save_locs"):
            parameters, results = self.ap.picasso_pick_kinetics(
                0, {"picks_file": "picks.yaml"}
            )
        self.assertEqual(3, mock_pk.call_args[1]["max_dark_time"])
        self.assertEqual(6.0, results["mean_length_frames"])
        self.assertEqual(15.0, results["mean_dark_frames"])
        self.assertEqual(1, results["n_picks_kept"])
        self.assertIs(self.ap.locs, out_locs)

    @patch("picasso_workflow.picasso_set.analyse_picks.io.save_locs")
    @patch(
        "picasso_workflow.picasso_set.analyse_picks."
        "postprocess.calculate_fret"
    )
    @patch("picasso_workflow.picasso_set.analyse_picks.io.load_locs")
    def test_picasso_fret(self, mock_ll, mock_fret, mock_sl):
        mock_ll.return_value = (self.ap.locs, [{"Frames": 10}])
        mock_fret.return_value = (
            {
                "fret_events": np.array([0.5, 0.7]),
                "fret_timepoints": np.array([1, 2]),
            },
            self.ap.locs.iloc[:2],
        )
        parameters, results = self.ap.picasso_fret(
            0,
            {"acc_locs_file": "acc.hdf5", "don_locs_file": "don.hdf5"},
        )
        self.assertEqual(2, results["n_fret_events"])
        self.assertAlmostEqual(0.6, results["mean_fret"])
        mock_sl.assert_called_once()
        self.assertTrue(os.path.isfile(results["filepath_fret_events"]))

    @patch(
        "picasso_workflow.picasso_set.analyse_picks."
        "postprocess.calculate_fret"
    )
    @patch("picasso_workflow.picasso_set.analyse_picks.io.load_locs")
    def test_picasso_fret_no_events(self, mock_ll, mock_fret):
        mock_ll.return_value = (self.ap.locs, [{"Frames": 10}])
        mock_fret.return_value = ({"fret_events": []}, [])
        parameters, results = self.ap.picasso_fret(
            0,
            {"acc_locs_file": "acc.hdf5", "don_locs_file": "don.hdf5"},
        )
        self.assertFalse(results["success"])

    @patch("picasso_workflow.picasso_set.analyse_picks.io.save_locs")
    @patch("picasso.masking.mask_locs")
    @patch("picasso.masking.mask_image")
    @patch("picasso.masking.generate_image")
    def test_picasso_mask_locs(self, mock_gi, mock_mi, mock_ml, mock_sl):
        mock_gi.return_value = np.random.rand(8, 8)
        mock_mi.return_value = (np.ones((8, 8), dtype=bool), 0.5)
        mock_ml.return_value = (self.ap.locs.iloc[:6], self.ap.locs.iloc[6:])
        with patch.object(self.ap, "_save_locs"):
            parameters, results = self.ap.picasso_mask_locs(
                0, {"disp_px_size": 100.0, "blur": 2.0}
            )
        # library default thresholding method
        self.assertEqual("otsu", mock_mi.call_args[0][1])
        self.assertEqual(6, results["nlocs_in"])
        self.assertEqual(4, results["nlocs_out"])
        self.assertEqual(0.5, results["threshold"])
        self.assertEqual(6, len(self.ap.locs))
        self.assertTrue(os.path.isfile(results["filepath_mask"]))
        self.assertTrue(os.path.isfile(results["fp_fig_mask"]))

    @patch("picasso_workflow.picasso_set.analyse_picks.postprocess.nena")
    def test_picasso_nena(self, mock_nena):
        self.ap.info.append({"Pixelsize": 130})
        mock_nena.return_value = ({"best_vals": None}, 0.4)
        parameters, results = self.ap.picasso_nena(0, {})
        self.assertAlmostEqual(0.4, results["nena_px"])
        self.assertAlmostEqual(52.0, results["nena_nm"])

    @patch("picasso_workflow.picasso_set.analyse_picks.postprocess.frc")
    def test_picasso_frc(self, mock_frc):
        freqs = np.linspace(0.001, 0.05, 50)
        mock_frc.return_value = {
            "frequencies": freqs,
            "frc_curve": np.random.rand(50),
            "frc_curve_smooth": np.random.rand(50),
            "resolution": 25.0,
            "images": None,
        }
        parameters, results = self.ap.picasso_frc(0, {})
        # full-FOV viewport from the metadata
        self.assertEqual(((0, 0), (32, 64)), mock_frc.call_args[0][2])
        self.assertEqual(42, mock_frc.call_args[1]["random_seed"])
        self.assertEqual(25.0, results["resolution_nm"])
        self.assertTrue(os.path.isfile(results["fp_fig_frc"]))
        self.assertTrue(os.path.isfile(results["filepath_frc"]))

    @patch(
        "picasso_workflow.picasso_set.analyse_core."
        "postprocess.compute_local_density"
    )
    def test_picasso_density(self, mock_cld):
        mock_cld.return_value = self.ap.locs
        with patch.object(self.ap, "_save_locs") as mock_save:
            parameters, results = self.ap.picasso_density(0, {"radius": 1.5})

        mock_cld.assert_called_once()
        self.assertEqual(1.5, mock_cld.call_args[0][2])
        self.assertTrue(results["success"])
        self.assertEqual(len(self.ap.locs), results["nlocs"])
        # saved like the CLI's _density.hdf5 output
        self.assertEqual(
            os.path.join(results["folder"], "locs_density.hdf5"),
            results["filepath_locs_density"],
        )
        mock_save.assert_any_call(results["filepath_locs_density"])
        # info entry mirrors the CLI
        self.assertIn("Density", self.ap.info[-1]["Generated by"])
        self.assertEqual(1.5, self.ap.info[-1]["Radius"])
        self.assertTrue(os.path.isdir(results["folder"]))


class TestPicassoSetGenericReporter(unittest.TestCase):
    """The generic reporter fallback serves every picasso-set module."""

    @patch("picasso_workflow.confluence.ConfluenceInterface")
    def setUp(self, mock_cfi):
        mock_instance = MagicMock()
        mock_instance.create_page.return_value = 534
        mock_instance.update_page_content.return_value = None
        mock_cfi.return_value = mock_instance
        self.cr = confluence.ConfluenceReporter(
            "url", "space", "parentpage", "my test report"
        )
        self.result_folder = tempfile.mkdtemp()

    def tearDown(self):
        shutil.rmtree(self.result_folder, ignore_errors=True)

    def _typical_results(self):
        fp_fig = os.path.join(self.result_folder, "plot.png")
        open(fp_fig, "w").close()
        fp_locs = os.path.join(self.result_folder, "locs_density.hdf5")
        open(fp_locs, "w").close()
        return {
            "folder": self.result_folder,
            "start time": "now",
            "end time": "later",
            "duration": 65.5,
            "nlocs": 1234,
            "filepath_locs_density": fp_locs,
        }

    def test_all_picasso_set_modules_resolve(self):
        for name in sorted(_picasso_set_names()):
            self.assertTrue(callable(getattr(self.cr, name)))

    def test_unknown_names_still_raise(self):
        with self.assertRaises(AttributeError):
            self.cr.not_a_module
        with self.assertRaises(AttributeError):
            self.cr._picasso_private_probe

    def test_generic_report_content(self):
        results = self._typical_results()
        text = self.cr.picasso_density(
            3, {"radius": 1.5}, results, postpone_report=True
        )
        self.assertIn("Module 03: picasso_density", text)
        self.assertIn("compute_local_density", text)
        self.assertIn("radius", text)
        # image embedded, non-image output listed
        self.assertIn("plot.png", text)
        self.assertIn("locs_density.hdf5", text)

    def test_generic_report_posts(self):
        results = self._typical_results()
        retval = self.cr.picasso_density(3, {"radius": 1.5}, results)
        self.assertIsNone(retval)
        self.cr.ci.upload_attachment.assert_called()
        self.cr.ci.update_page_content.assert_called()

    def test_generic_report_without_folder(self):
        # must not fail when the folder is gone (e.g. moved results)
        text = self.cr.picasso_density(
            1,
            {"radius": 1.5},
            {"folder": "/nonexistent", "duration": 1.0},
            postpone_report=True,
        )
        self.assertIn("Module 01: picasso_density", text)


class TestPicassoSetHtmlReporter(unittest.TestCase):
    """HTMLReporter inherits the generic picasso-set reporting."""

    def setUp(self):
        self.report_dir = tempfile.mkdtemp()
        self.hr = html_reporter.HTMLReporter(
            self.report_dir, "picasso set report"
        )

    def tearDown(self):
        shutil.rmtree(self.report_dir, ignore_errors=True)

    def test_generic_report_renders(self):
        result_folder = os.path.join(self.report_dir, "00_picasso_density")
        os.makedirs(result_folder)
        fp_fig = os.path.join(result_folder, "plot.png")
        open(fp_fig, "w").close()
        results = {
            "folder": result_folder,
            "duration": 3.0,
            "nlocs": 12,
        }
        self.hr.picasso_density(0, {"radius": 1.5}, results)
        report_file = self.hr.ci.html_path
        with open(report_file, encoding="utf-8") as f:
            content = f.read()
        self.assertIn("picasso_density", content)
        self.assertIn("plot.png", content)


if __name__ == "__main__":
    unittest.main()
