# default located in picasso-workflow/picasso_workflow folder
# user-specific version can be in ~/.config/picasso_workflow/config.yaml or %APPDATA%\picasso_workflow\config.yaml
Templates:
  TemplateName: "/local/path/to/template"
Confluence:
  URL: ""
  Space: "~user"
  DefaultPage: ""
SlurmDefault:
  nodes: 2
  cores: 12
  memory: "50GB"
  timeout: "24:00:00"
SlurmLoginNodes:
  clusterXXX: cluster001
Drivepaths:
  machine.local:
    - "/local/machine/path"
  clusterXXX:
    - "/analogue/path/on/cluster"
  awindowsmachineXX:
    - "C:"
