#!/usr/bin/env python
"""Tier 1 of the picasso-set: core pipeline modules.

:class:`PicassoSetCoreMixin` contributes the ``picasso_*`` core-pipeline
modules (localize, undrift, link, clustering, render, ...) to
:class:`~picasso_workflow.analyse.AutoPicasso`. Each module mirrors the
corresponding picasso CLI command with identical parameter names and
defaults, operating on the shared ``self.locs`` / ``self.info`` state like
the classic modules, so the two sets mix freely in one workflow.

Author: Heinrich Grabmayr
Initial date: October 5, 2026
"""

from __future__ import annotations

import os

from picasso import __version__ as picassoversion
from picasso import postprocess

from picasso_workflow.module_runtime import module_decorator


class PicassoSetCoreMixin:
    """Core-pipeline picasso-set modules (mixin for ``AutoPicasso``)."""

    @module_decorator
    def picasso_density(self, i, parameters, results):
        """Compute the local localization density (native CLI: density).

        Wraps ``picasso.postprocess.compute_local_density`` exactly like the
        ``picasso density`` CLI command: annotates every localization with
        the number of neighbors within ``radius`` and saves the result as
        ``locs_density.hdf5`` (the CLI's ``_density.hdf5`` output).

        Parameters
        ----------
        i : int
            Index of the module in the workflow.
        parameters : dict
            Required keys:

            ``radius`` : float
                Maximum distance (camera pixels) for localizations to count
                as local.
        results : dict
            Module results (see
            :class:`~picasso_workflow.util.AbstractModuleCollection`).
        """
        radius = float(parameters["radius"])
        self.locs = postprocess.compute_local_density(
            self.locs, self.info, radius
        )
        density_info = {
            "Generated by": f"Picasso v{picassoversion} Density",
            "Radius": radius,
            "Wrapped by": "picasso-workflow : picasso_density",
        }
        self.info.append(density_info)
        fp = os.path.join(results["folder"], "locs_density.hdf5")
        self._save_locs(fp)
        results["filepath_locs_density"] = fp
        results["nlocs"] = len(self.locs)
        return parameters, results
