name: Python Unit Tests and Coverage

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop

jobs:
  test:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python A
        run: |
          Invoke-WebRequest -Uri https://github.com/actions/python-versions/releases/download/3.10.11-4626646535/python-3.10.11-win32-x64.zip -OutFile python-3.10.zip
          Expand-Archive -Path 'python-3.10.zip' -DestinationPath 'python3-10' -Force
          dir
          cd python3-10
          dir
          .\setup.ps1
          $Env:Path += ";C:\actions-runner\_work\_tool\Python\3.10.11\x64"
          dir C:\actions-runner\_work\_tool\Python\3.10.11\x64
          # python3 --version
          # New-Item -ItemType SymbolicLink -Path "python" -Target "python3"
          python --version
          python -m pip install --upgrade pip
          dir c:\actions-runner\_work\_tool\python\3.10.11\x64\lib\site-packages
          
      # - name: Set up Python B
      #   uses: actions/setup-python@v5
      #   with:
      #     python-version: '3.10'

      - name: Install dependencies
        run: |
          $Env:Path += ";C:\actions-runner\_work\_tool\Python\3.10.11\x64;C:\actions-runner\_work\_tool\python\3.10.11\x64\lib\site-packages"
          python --version
          pip install -r requirements.txt

