name: Python Unit Tests and Coverage

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop

jobs:
  test:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python A
        run: |
          Invoke-WebRequest -Uri https://github.com/actions/python-versions/releases/download/3.10.11-4626646535/python-3.10.11-win32-x64.zip -OutFile python-3.10.zip
          Expand-Archive -Path 'python-3.10.zip' -DestinationPath 'python3-10' -Force
          dir
          dir python3-10
          Start-Process -Wait -FilePath python-3.10.0.exe -ArgumentList '/quiet InstallAllUsers=1 PrependPath=1'
          python3 -m pip install --upgrade pip
          
      - name: Set up Python B
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python --version
          pip install -r requirements.txt

