name: Python Unit Tests and Coverage

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop

jobs:
  test:
    runs-on: self-hosted
    strategy:
      matrix:
        python-version: [3.10]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        run: |
          Invoke-WebRequest -Uri https://www.python.org/ftp/python/3.10.0/python-3.10.0-amd64.exe -OutFile python-3.10.0.exe
          dir
          Start-Process -Wait -FilePath python-3.10.0.exe -ArgumentList '/quiet InstallAllUsers=1 PrependPath=1'
          Start-Process -Wait python -ArgumentList '-m pip install --upgrade pip'

      - name: Install dependencies
        run: Start-Process -Wait pip -ArgumentList 'install -r requirements.txt'

      - name: Run unit tests
        run: Start-Process -Wait pytest

      - name: Generate coverage report
        run: Start-Process -Wait coverage -ArgumentList 'run -m pytest'

      - name: Print coverage report
        run: Start-Process -Wait coverage -ArgumentList 'report'
